// Generated by scripts/generate-registry.ts — list of all registry tables.
import type { TableDef } from "./types";
import { projects } from "./tables/projects";
import { contacts } from "./tables/contacts";
import { contactInteractions } from "./tables/contact_interactions";
import { buildings } from "./tables/buildings";
import { permits } from "./tables/permits";
import { organizations } from "./tables/organizations";
import { punchListItems } from "./tables/punch_list_items";
import { employees } from "./tables/employees";
import { vehicles } from "./tables/vehicles";
import { tasks } from "./tables/tasks";
import { rmas } from "./tables/rmas";
import { transactions } from "./tables/transactions";
import { inventoryCheckouts } from "./tables/inventory_checkouts";
import { payouts } from "./tables/payouts";
import { products } from "./tables/products";
import { sales } from "./tables/sales";
import { stockItems } from "./tables/stock_items";
import { supportTickets } from "./tables/support_tickets";
import { supportNotes } from "./tables/support_notes";
import { kbArticles } from "./tables/kb_articles";
import { suppliers } from "./tables/suppliers";
import { brands } from "./tables/brands";
import { kbCategories } from "./tables/kb_categories";
import { jobReports } from "./tables/job_reports";
import { formNotes } from "./tables/form_notes";
import { staffPerformance } from "./tables/staff_performance";
import { surveyProposals } from "./tables/survey_proposals";
import { tvInstallations } from "./tables/tv_installations";

export const REGISTRY: TableDef[] = [
  projects,
  contacts,
  contactInteractions,
  buildings,
  permits,
  organizations,
  punchListItems,
  employees,
  vehicles,
  tasks,
  rmas,
  transactions,
  inventoryCheckouts,
  payouts,
  products,
  sales,
  stockItems,
  supportTickets,
  supportNotes,
  kbArticles,
  suppliers,
  brands,
  kbCategories,
  jobReports,
  formNotes,
  staffPerformance,
  surveyProposals,
  tvInstallations,
];

const BY_NAME = new Map(REGISTRY.map((t) => [t.name, t]));

export function getTable(name: string): TableDef {
  const t = BY_NAME.get(name);
  if (!t) throw new Error(`Unknown table ${name}`);
  return t;
}
