// Generated by scripts/generate-registry.ts — list of all registry tables.
import type { TableDef } from "./types";
import { projects } from "./tables/projects";
import { contacts } from "./tables/contacts";
import { contactInteractions } from "./tables/contact_interactions";
import { buildings } from "./tables/buildings";
import { permits } from "./tables/permits";
import { organizations } from "./tables/organizations";
import { punchListItems } from "./tables/punch_list_items";
import { employees } from "./tables/employees";
import { vehicles } from "./tables/vehicles";
import { tasks } from "./tables/tasks";
import { rmas } from "./tables/rmas";
import { transactions } from "./tables/transactions";
import { inventoryCheckouts } from "./tables/inventory_checkouts";
import { payouts } from "./tables/payouts";
import { products } from "./tables/products";
import { sales } from "./tables/sales";
import { stockItems } from "./tables/stock_items";
import { suppliers } from "./tables/suppliers";
import { brands } from "./tables/brands";
import { jobReports } from "./tables/job_reports";
import { formNotes } from "./tables/form_notes";
import { staffPerformance } from "./tables/staff_performance";
import { surveyProposals } from "./tables/survey_proposals";
import { tvInstallations } from "./tables/tv_installations";
import { visits } from "./tables/visits";
import { reportDeficiencies } from "./tables/report_deficiencies";
import { companyDocuments } from "./tables/company_documents";

/** Tables carried over from WebAuthor (the parity tests check these against the export). TS Help Desk was removed (SPEC §9.1 H-a). */
export const WEBAUTHOR_REGISTRY: TableDef[] = [
  projects,
  contacts,
  contactInteractions,
  buildings,
  permits,
  organizations,
  punchListItems,
  employees,
  vehicles,
  tasks,
  rmas,
  transactions,
  inventoryCheckouts,
  payouts,
  products,
  sales,
  stockItems,
  suppliers,
  brands,
  jobReports,
  formNotes,
  staffPerformance,
  surveyProposals,
  tvInstallations,
];

/** Tables built for this CRM (Portal features, docs/portal-features-merge.md). */
export const NEW_TABLES: TableDef[] = [visits, reportDeficiencies, companyDocuments];

export const REGISTRY: TableDef[] = [...WEBAUTHOR_REGISTRY, ...NEW_TABLES];

const BY_NAME = new Map(REGISTRY.map((t) => [t.name, t]));

export function getTable(name: string): TableDef {
  const t = BY_NAME.get(name);
  if (!t) throw new Error(`Unknown table ${name}`);
  return t;
}
