/**
 * Generates the record-table migration from the registry (M4).
 *
 *   npx tsx scripts/generate-schema.ts <output.sql>
 *
 * Output is a migration: once applied, never regenerate it in place — add a new
 * migration for later schema changes.
 */
import { writeFileSync } from "node:fs";
import { REGISTRY, getTable } from "../src/registry";
import type { FieldDef, TableDef } from "../src/registry/types";
import { NO_COLUMN_TYPES, joinTableName, permissionResource, lockResource, projectFinancialsColumns } from "./lib/schema-map";

const out = process.argv[2];
if (!out) throw new Error("usage: tsx scripts/generate-schema.ts <output.sql>");

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const ident = (s: string) => (/^[a-z_][a-z0-9_]*$/.test(s) ? s : `"${s}"`);

function columnType(f: FieldDef): string {
  switch (f.type) {
    case "checkboxes":
      return "text[] not null default '{}'";
    case "boolean":
      return `boolean not null default ${f.default === true}`;
    case "date":
      return f.default === "today" ? "date default ((now() at time zone 'America/New_York')::date)" : "date";
    case "datetime":
      return f.default === "now" ? "timestamptz default now()" : "timestamptz";
    case "money":
      return "numeric(12,2)";
    case "number":
      return "integer";
    case "address":
      return "jsonb";
    case "user":
      return "uuid references public.profiles (id) on delete set null";
    case "lookup":
      return "bigint"; // foreign key added after all tables exist
    default:
      return typeof f.default === "string" && f.default !== "today" && f.default !== "now" ? `text default ${q(f.default)}` : "text";
  }
}

const isJoin = (f: FieldDef) => (f.type === "lookup" || f.type === "group") && f.multiple;

const lines: string[] = [
  "-- GENERATED by scripts/generate-schema.ts from src/registry (M4). Do not edit by hand;",
  "-- once applied, change the schema with a new migration.",
  "",
];
const fks: string[] = [];
const indexes: string[] = [];
const joins: string[] = [];
const security: string[] = [];
const catalogue: string[] = [];

for (const t of REGISTRY) {
  const cols: string[] = ["  id bigint generated by default as identity primary key"];
  const hasTitleField = t.fields.some((f) => f.name === "title");
  if (!hasTitleField) cols.push("  title text");

  for (const f of t.fields) {
    if (NO_COLUMN_TYPES.includes(f.type) || isJoin(f)) continue;
    if (t.parent && f.name === t.parent.field) {
      cols.push(`  ${f.name} bigint not null`);
      fks.push(`alter table public.${t.name} add foreign key (${f.name}) references public.${t.parent.table} (id) on delete cascade;`);
      indexes.push(`create index on public.${t.name} (${f.name});`);
      continue;
    }
    cols.push(`  ${ident(f.name)} ${columnType(f)}`);
    if (f.type === "lookup" && f.lookup) {
      fks.push(`alter table public.${t.name} add foreign key (${f.name}) references public.${f.lookup.table} (id) on delete set null;`);
      indexes.push(`create index on public.${t.name} (${f.name});`);
    }
    if (f.type === "user") indexes.push(`create index on public.${t.name} (${f.name});`);
  }

  cols.push(
    "  locked boolean not null default false",
    "  submitted_at timestamptz",
    "  created_at timestamptz not null default now()",
    "  created_by uuid default auth.uid() references public.profiles (id) on delete set null",
    "  updated_at timestamptz not null default now()",
    "  updated_by uuid default auth.uid() references public.profiles (id) on delete set null",
    "  archived_at timestamptz",
    "  deleted_at timestamptz",
  );

  lines.push(`-- ${t.label} (WebAuthor ${t.legacy.table})`, `create table public.${t.name} (`, cols.join(",\n"), ");");
  lines.push(`comment on table public.${t.name} is ${q(`${t.label} — WebAuthor ${t.legacy.table}`)};`);
  for (const f of t.fields) {
    if (NO_COLUMN_TYPES.includes(f.type) || isJoin(f)) continue;
    const note = f.sensitive ? " (sensitive: stored encrypted by the app)" : "";
    lines.push(`comment on column public.${t.name}.${ident(f.name)} is ${q(f.label + note)};`);
  }
  indexes.push(`create index on public.${t.name} (created_by);`, `create index on public.${t.name} (updated_at desc);`);
  lines.push("");

  // Many-to-many lookups → link tables (record_id, target_id).
  for (const f of t.fields.filter(isJoin)) {
    const jt = joinTableName(t.name, f.name);
    const target = f.type === "group" ? { table: "groups", idType: "smallint" } : { table: f.lookup!.table, idType: "bigint" };
    joins.push(
      `-- ${t.label} › ${f.label} (many)`,
      `create table public.${jt} (`,
      `  record_id bigint not null references public.${t.name} (id) on delete cascade,`,
      `  target_id ${target.idType} not null references public.${target.table} (id) on delete cascade,`,
      `  created_at timestamptz not null default now(),`,
      `  primary key (record_id, target_id)`,
      `);`,
      `create index on public.${jt} (target_id);`,
      `comment on table public.${jt} is ${q(`${t.label} › ${f.label}`)};`,
      `alter table public.${jt} enable row level security;`,
      `create policy "view" on public.${jt} for select to authenticated using (exists (select 1 from public.${t.name} r where r.id = record_id));`,
      `create policy "change" on public.${jt} for insert to authenticated with check (exists (select 1 from public.${t.name} r where r.id = record_id) and (select app.can_do('${t.name}', 'modify')));`,
      `create policy "remove" on public.${jt} for delete to authenticated using (exists (select 1 from public.${t.name} r where r.id = record_id) and (select app.can_do('${t.name}', 'modify')));`,
      "",
    );
  }

  // Catalogue row used by the permission functions.
  const sensitive = t.fields.filter((f) => f.sensitive).map((f) => f.name);
  const resource = permissionResource(t);
  const lock = lockResource(t);
  catalogue.push(
    `  (${q(t.name)}, ${q(t.label)}, ${q(t.module)}, ${resource ? q(resource) : "null"}, ${t.parent ? q(t.parent.table) : "null"}, ${
      t.parent ? q(t.parent.field) : "null"
    }, ${lock ? q(lock) : "null"}, ${sensitive.length ? `array[${sensitive.map(q).join(", ")}]` : "'{}'"})`,
  );

  // Triggers + RLS.
  security.push(
    `-- ${t.label}`,
    `create trigger before_write before insert or update on public.${t.name} for each row execute function app.record_before_write();`,
    `create trigger audit after insert or update on public.${t.name} for each row execute function app.record_audit();`,
    `alter table public.${t.name} enable row level security;`,
  );
  if (t.parent) {
    const parentVisible = `exists (select 1 from public.${t.parent.table} p where p.id = ${t.parent.field})`;
    security.push(
      `create policy "view" on public.${t.name} for select to authenticated using (${parentVisible});`,
      `create policy "create" on public.${t.name} for insert to authenticated with check (${parentVisible} and (select app.can_do('${t.name}', 'create')));`,
      `create policy "modify" on public.${t.name} for update to authenticated using (${parentVisible} and (select app.can_do('${t.name}', 'modify'))) with check (${parentVisible});`,
    );
  } else if (!resource) {
    security.push(
      `create policy "view" on public.${t.name} for select to authenticated using (true);`,
      `create policy "create" on public.${t.name} for insert to authenticated with check ((select app.can_manage_utility()));`,
      `create policy "modify" on public.${t.name} for update to authenticated using ((select app.can_manage_utility())) with check ((select app.can_manage_utility()));`,
    );
  } else {
    const view = `((select app.can_view_all('${t.name}')) or (created_by = (select auth.uid()) and (select app.can_view_page('${t.name}'))))`;
    const anyChange = `((select app.can_do('${t.name}', 'modify')) or (select app.can_do('${t.name}', 'delete')) or (select app.can_do('${t.name}', 'archive')))`;
    security.push(
      `create policy "view" on public.${t.name} for select to authenticated using ${view};`,
      `create policy "create" on public.${t.name} for insert to authenticated with check ((select app.can_do('${t.name}', 'create')));`,
      `create policy "modify" on public.${t.name} for update to authenticated using (${view} and ${anyChange}) with check (${anyChange});`,
    );
  }
  security.push("");
}

lines.push("-- ---------------------------------------------------------------- links between tables", ...fks, "");
lines.push("-- ---------------------------------------------------------------- many-to-many link tables", ...joins);
lines.push("-- ---------------------------------------------------------------- indexes", ...indexes, "");
lines.push(
  "-- ---------------------------------------------------------------- permission catalogue",
  "insert into app.record_types (table_name, label, module, resource, parent_table, parent_column, lock_resource, sensitive_columns) values",
  catalogue.join(",\n") + ";",
  "",
);
lines.push("-- ---------------------------------------------------------------- triggers and row-level security", ...security);

// Projects › Approved / Invoiced / Paid (SPEC §2.3). Empty sums count as 0 (SPEC §9.1 Q7).
const fin = projectFinancialsColumns(getTable("projects"));
lines.push(
  "-- ---------------------------------------------------------------- computed fields",
  "-- Projects › Approved / Invoiced / Paid: sums of Transactions (SPEC §2.3). Runs with owner rights so the",
  "-- totals show even to people who can't open Transactions, but only for projects the caller may see.",
  "create function public.project_financials(p_project_ids bigint[])",
  `returns table (project_id bigint, ${fin.map((c) => `${c.name} numeric`).join(", ")})`,
  "language sql stable security definer set search_path = ''",
  "as $$",
  "  select p.id,",
  fin
    .map((c) => `    coalesce(sum(t.amount) filter (where t.type = ${q(c.type)}), 0)`)
    .join(",\n"),
  "  from public.projects p",
  "  left join public.transactions t on t.project_id = p.id and t.deleted_at is null",
  "  where p.id = any (p_project_ids)",
  "    and (app.can_view_all('projects') or (p.created_by = auth.uid() and app.can_view_page('projects')))",
  "  group by p.id;",
  "$$;",
  "revoke execute on function public.project_financials(bigint[]) from public, anon;",
  "grant execute on function public.project_financials(bigint[]) to authenticated;",
  "",
);

writeFileSync(out, lines.join("\n"), "utf8");
console.log(`${REGISTRY.length} tables, ${joins.filter((l) => l.startsWith("create table")).length} link tables → ${out}`);

export type { TableDef };
