/**
 * Generates the SQL that seeds groups, the permission catalogue and group grants
 * from techsquad_crm_spec.json.
 *
 *   npx tsx scripts/generate-permissions.ts <output.sql>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { buildPermissions, GROUPS } from "./lib/permissions-map";

const out = process.argv[2];
if (!out) throw new Error("usage: tsx scripts/generate-permissions.ts <output.sql>");

const spec = JSON.parse(readFileSync("techsquad_crm_spec.json", "utf8"));
const perms = buildPermissions(spec);

const q = (s: string | null) => (s === null ? "null" : `'${s.replace(/'/g, "''")}'`);

const lines: string[] = [
  "-- GENERATED by scripts/generate-permissions.ts from techsquad_crm_spec.json. Do not edit by hand.",
  "-- Seeds the 12 groups, the permission catalogue and each group's grants (SPEC §7).",
  "",
  "insert into public.groups (slug, name, legacy_code, is_system) values",
  GROUPS.map((g) => `  (${q(g.slug)}, ${q(g.name)}, ${q(g.legacyCode)}, ${g.isSystem})`).join(",\n") +
    "\non conflict (slug) do nothing;",
  "",
  "insert into public.permissions (key, module, resource, action, kind, area, label, description) values",
  perms
    .map(
      (p) =>
        `  (${q(p.key)}, ${q(p.module)}, ${q(p.resource)}, ${q(p.action)}, ${q(p.kind)}, ${q(p.area)}, ${q(p.label)}, ${q(p.description)})`,
    )
    .join(",\n") + "\non conflict (key) do nothing;",
  "",
  "insert into public.group_permissions (group_id, permission_key)",
  "select g.id, v.permission_key from (values",
  perms
    .flatMap((p) => p.groups.map((g) => `  (${q(g)}, ${q(p.key)})`))
    .join(",\n"),
  ") as v(group_slug, permission_key)",
  "join public.groups g on g.slug = v.group_slug",
  "on conflict do nothing;",
  "",
];

writeFileSync(out, lines.join("\n"), "utf8");
console.log(`${perms.length} permissions, ${perms.reduce((n, p) => n + p.groups.length, 0)} grants → ${out}`);
