-- F20 Forgotten check-outs (SPEC §9.1 F20, Fred 2026-10-05):
-- 1. Starting another visit (On my way / Check in) checks the technician out of any visit still "On site",
--    so one person is never on site in two places; clocking out for the day does the same.
-- 2. After midnight the tick checks out whoever is still on site, at the day's cut-off (4 PM, 5 PM for
--    the people in the late list; Admin › Field day), and clocks out an open time-clock day the same way.
-- 3. Each forgotten check-out / clock-out / missing report becomes a warning the person must acknowledge
--    before using the CRM the next day.

alter table public.visits
  add column auto_closed_at timestamptz,
  add column auto_closed_reason text check (auto_closed_reason in ('next_visit', 'clock_out', 'end_of_day'));
comment on column public.visits.auto_closed_reason is 'F20: set when the system checked the visit out (next_visit = the technician started another visit, clock_out = clocked out for the day, end_of_day = forgotten, closed after midnight at the cut-off time)';

create table public.field_warnings (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees (id) on delete cascade,
  user_id uuid references public.profiles (id) on delete cascade,
  kind text not null check (kind in ('forgot_checkout', 'forgot_clock_out', 'missing_report')),
  day date not null,
  visit_id bigint references public.visits (id) on delete cascade,
  project text,
  closed_at timestamptz,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now(),
  unique nulls not distinct (employee_id, kind, day, visit_id)
);
create index on public.field_warnings (user_id) where acknowledged_at is null;
comment on table public.field_warnings is 'F20: forgotten check-outs, clock-outs and missing reports found after midnight; the person acknowledges them before using the CRM (acknowledged_at).';
alter table public.field_warnings enable row level security;
create policy "own warnings" on public.field_warnings for select to authenticated using (user_id = (select auth.uid()));
create policy "acknowledge own warnings" on public.field_warnings for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
grant select, update on public.field_warnings to authenticated;

-- Check me out of every other visit I am still on (my own Employee records, by login email).
create or replace function public.close_my_open_visits(p_except bigint, p_reason text)
returns integer
language plpgsql security definer set search_path = ''
as $$
declare
  me text := (select lower(email) from auth.users where id = auth.uid());
  n integer := 0;
begin
  if me is null then
    return 0;
  end if;
  perform set_config('app.engine', 'on', true);
  with mine as (
    select id from public.employees where lower(email) = me and deleted_at is null
  ), closed as (
    update public.visits v
       set status = 'Done', checked_out_at = now(), auto_closed_at = now(), auto_closed_reason = p_reason, updated_by = auth.uid()
     where v.technician_id in (select id from mine)
       and v.checked_in_at is not null and v.checked_out_at is null
       and v.deleted_at is null and coalesce(v.status, '') <> 'Cancelled'
       and v.id <> coalesce(p_except, 0)
    returning v.id
  )
  select count(*) into n from closed;
  perform set_config('app.engine', 'off', true);
  return n;
end;
$$;
grant execute on function public.close_my_open_visits(bigint, text) to authenticated;

-- visit_step (F2) now closes the technician's other open visits when a new one starts.
create or replace function public.visit_step(p_id bigint, p_step text)
returns public.visits
language plpgsql security definer set search_path = ''
as $$
declare
  v public.visits;
  me text := (select lower(email) from auth.users where id = auth.uid());
  going boolean;
  items jsonb;
begin
  select * into v from public.visits where id = p_id and deleted_at is null;
  if v.id is null then
    raise exception 'This visit no longer exists' using errcode = 'P0002';
  end if;
  select exists (
    select 1 from public.employees e
    where lower(e.email) = me and e.deleted_at is null
      and (e.id = v.technician_id or e.id in (select target_id from public.visits_team where record_id = p_id))
  ) into going;
  if not (going or app.can_do('visits', 'modify')) then
    raise exception 'Only the people going on this visit can check in or out' using errcode = '42501';
  end if;
  if v.status = 'Cancelled' then
    raise exception 'This visit was cancelled' using errcode = '22023';
  end if;

  -- F20: one person on site in one place only.
  if p_step in ('on_way', 'check_in') then
    perform public.close_my_open_visits(p_id, 'next_visit');
  end if;

  perform set_config('app.engine', 'on', true);
  case p_step
    when 'on_way' then
      update public.visits set status = 'On the way', on_way_at = now(), updated_by = auth.uid() where id = p_id returning * into v;
    when 'check_in' then
      update public.visits set status = 'On site', checked_in_at = coalesce(checked_in_at, now()), updated_by = auth.uid() where id = p_id returning * into v;
      items := (select value -> 'service_lists' -> v.service_type -> 'checklist' from public.app_settings where key = 'field_day');
      if v.service_type is not null and jsonb_typeof(items) = 'array' then
        insert into public.record_checklist_items (table_name, record_id, item, source, created_by)
        select 'visits', p_id, trim(x), 'service:' || v.service_type, null
        from jsonb_array_elements_text(items) x
        where trim(x) <> ''
          and not exists (select 1 from public.record_checklist_items c where c.table_name = 'visits' and c.record_id = p_id and c.item = trim(x));
      end if;
    when 'check_out' then
      update public.visits set status = 'Done', checked_in_at = coalesce(checked_in_at, now()), checked_out_at = now(), updated_by = auth.uid() where id = p_id returning * into v;
    else
      raise exception 'Unknown step %', p_step using errcode = '22023';
  end case;
  perform set_config('app.engine', 'off', true);
  return v;
end;
$$;

-- Cut-off times: 4 PM for everyone, 5 PM for the people Fred named (Jessica 1004, Luana 1005, Lucas 1006, Saulo 1012).
insert into public.app_settings (key, value)
values ('field_day', jsonb_build_object('time_clock', jsonb_build_object('auto_checkout', jsonb_build_object('time', '16:00', 'late_time', '17:00', 'late_employee_ids', jsonb_build_array(1004, 1005, 1006, 1012)))))
on conflict (key) do update
  set value = public.app_settings.value || jsonb_build_object(
    'time_clock',
    coalesce(public.app_settings.value -> 'time_clock', '{}'::jsonb) || jsonb_build_object('auto_checkout', jsonb_build_object('time', '16:00', 'late_time', '17:00', 'late_employee_ids', jsonb_build_array(1004, 1005, 1006, 1012)))
  );
