-- P2 Time clock + employee performance (Fred 2026-10-02, SPEC §9.1 P2-a…e).
-- Clock in / out and visit check-ins with the phone's position; performance reports with aspect and
-- weight; skills per employee; a cache of geocoded addresses for "at the office" / "on site".

-- ---------------------------------------------------------------- time entries
create table public.time_entries (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  kind text not null check (kind in ('clock_in', 'clock_out', 'on_way', 'visit_in', 'visit_out')),
  at timestamptz not null default now(),
  visit_id bigint references public.visits (id) on delete set null,
  lat double precision,
  lng double precision,
  accuracy_m integer,
  place text not null default 'Unknown' check (place in ('Office', 'On site', 'Elsewhere', 'Unknown')),
  distance_m integer,
  note text,
  corrected_at timestamptz,
  corrected_by uuid references public.profiles (id) on delete set null,
  original_at timestamptz,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index on public.time_entries (employee_id, at desc);
create index on public.time_entries (at desc);
create index on public.time_entries (visit_id);
comment on table public.time_entries is 'Clock in / out and visit check-ins with the phone position at that moment (SPEC §9.1 P2-a).';
alter table public.time_entries enable row level security;

-- Everyone records their own; people who see all employees see everyone's; employee editors correct them.
create policy "own or employee viewers read" on public.time_entries
  for select to authenticated
  using (user_id = auth.uid() or app.has_permission('administrative.employees.view_all'));
create policy "record own" on public.time_entries
  for insert to authenticated
  with check (user_id = auth.uid());
create policy "employee editors correct" on public.time_entries
  for update to authenticated
  using (app.has_permission('administrative.employees.modify'))
  with check (app.has_permission('administrative.employees.modify'));

-- ---------------------------------------------------------------- geocoded addresses (cache)
create table public.geocodes (
  address text primary key,
  lat double precision not null,
  lng double precision not null,
  created_at timestamptz not null default now()
);
comment on table public.geocodes is 'Address → position, looked up once (Google Places) for the time clock.';
alter table public.geocodes enable row level security;
create policy "signed-in read" on public.geocodes for select to authenticated using (true);
create policy "signed-in add" on public.geocodes for insert to authenticated with check (true);

-- ---------------------------------------------------------------- employees: time clock group
alter table public.employees add column clock_group text not null default 'Field' check (clock_group in ('Field', 'Office'));
comment on column public.employees.clock_group is 'Time clock group: when the "still clocked in" reminder fires (Field 5 PM, Office 6 PM by default).';

-- ---------------------------------------------------------------- skills
create table public.employee_skills (
  employee_id bigint not null references public.employees (id) on delete cascade,
  skill text not null,
  level text not null check (level in ('Learning', 'Can do', 'Expert')),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles (id) on delete set null,
  primary key (employee_id, skill)
);
comment on table public.employee_skills is 'Skills per employee with a level (SPEC §9.1 P2-d).';
alter table public.employee_skills enable row level security;
create policy "employee viewers read" on public.employee_skills
  for select to authenticated
  using (app.has_permission('administrative.employees.view_page'));
create policy "performance viewers manage" on public.employee_skills
  for all to authenticated
  using (app.has_permission('forms.staff-performance.view_all'))
  with check (app.has_permission('forms.staff-performance.view_all'));

-- ---------------------------------------------------------------- performance reports: aspect, weight, links
alter table public.staff_performance
  add column aspect text,
  add column weight text,
  add column project_id bigint references public.projects (id) on delete set null,
  add column visit_id bigint references public.visits (id) on delete set null;
create index on public.staff_performance (employee_id, date desc);
comment on column public.staff_performance.aspect is 'What the report is about (Speed, Quality of work, Punctuality, …).';
comment on column public.staff_performance.weight is 'Minor / Normal / Major: how much the report moves the score.';
