-- F22-a (SPEC §9.1, Fred 2026-10-07): a technician who checked in or out at the wrong time asks for a
-- correction (the right time and why); Jessica, Fred, Luana or Saulo approve it from the alerts bell
-- or the visit page, and the visit's time is rewritten through the ordinary write path (audited).
create table public.time_corrections (
  id bigint generated by default as identity primary key,
  visit_id bigint not null references public.visits (id) on delete cascade,
  employee_id bigint not null references public.employees (id) on delete cascade,
  requested_by uuid not null references public.profiles (id) on delete cascade,
  field text not null check (field in ('on_way_at', 'checked_in_at', 'checked_out_at')),
  previous_at timestamptz,
  requested_at timestamptz not null,
  reason text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  decided_by uuid references public.profiles (id) on delete set null,
  decided_at timestamptz,
  decision_note text,
  created_at timestamptz not null default now()
);
create index on public.time_corrections (visit_id);
create index on public.time_corrections (status) where status = 'pending';
comment on table public.time_corrections is 'F22-a: check-in / check-out correction requests from technicians, approved by the office.';
alter table public.time_corrections enable row level security;
-- The requester sees their own requests; anyone who may change visits (the office) sees them all.
create policy "own or office" on public.time_corrections for select to authenticated
  using (requested_by = (select auth.uid()) or app.has_permission('schedule.visits.modify') or app.is_sysadmin());
grant select on public.time_corrections to authenticated;

-- F22-c (Fred 2026-10-07): each visit says whether it is part of the project or a service call billed on
-- its own; when a service call is Done, Accounting (Luana, employee #1005) gets a task to invoice it.
alter table public.visits add column if not exists billing text;
insert into public.automations (id, table_name, title, active, events, conditions, actions, notes)
values (
  900701, 'visits', 'Service call done: task for Accounting to bill it', true,
  '{field:status}',
  '{"match":"all","rules":[{"field":"status","op":"=","value":"Done"},{"field":"billing","op":"=","value":"Service call"}]}',
  '[{"type":"task","text":"Service call done, bill the client: {project_id} – visit of {starts_at} ({technician_id})","due_days":1,"employee_id":1005,"labels":["Client"]}]',
  'F22-c: a service call (visits.billing = Service call) that reaches Done creates a task for Accounting. Change employee_id here if someone else bills.'
)
on conflict (id) do nothing;
