-- Tagging people in notes (@Name) and the top-bar alerts (Fred 2026-09-30).
-- One row per person tagged in a note. The tagged person sees it in the alerts bell until they open it.

create table public.record_mentions (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.record_notes (id) on delete cascade,
  table_name text not null,
  record_id bigint not null,
  user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  seen_at timestamptz,
  unique (note_id, user_id)
);
create index record_mentions_user_idx on public.record_mentions (user_id) where seen_at is null;

alter table public.record_mentions enable row level security;

-- The tagged person reads their own tags; the author can see whom they tagged.
create policy "read own" on public.record_mentions for select to authenticated
  using (user_id = auth.uid() or created_by = auth.uid());
-- Only the note's author tags, on a record they can see, from their own note.
create policy "tag" on public.record_mentions for insert to authenticated
  with check (
    created_by = auth.uid()
    and app.record_visible(table_name, record_id)
    and exists (select 1 from public.record_notes n where n.id = note_id and n.created_by = auth.uid() and n.table_name = record_mentions.table_name and n.record_id = record_mentions.record_id)
  );
-- The tagged person marks it seen.
create policy "mark seen" on public.record_mentions for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

grant select, insert, update on public.record_mentions to authenticated;
