-- M9: workflows (SPEC §6, decisions of 2026-09-25):
--   Project Proposal — moved by Office Management, Project Manager, COO, Admin, System Administrators
--   Punch List       — moved by everyone who can edit punch items + Technicians
--   Stock Status     — moved by Admin, System Administrators; starts when a Stock record is created (Q10)
--   Help Desk        — imported but inactive (never used in WebAuthor)
-- Moving a record runs inside one database function (all-or-nothing), which may update the
-- record's status field even when the record is locked (submitted).

create table public.workflows (
  id text primary key,
  name text not null,
  table_name text not null unique,
  start_on text not null check (start_on in ('submit', 'create')),
  active boolean not null default true
);

create table public.workflow_levels (
  id bigint generated by default as identity primary key,
  workflow_id text not null references public.workflows (id) on delete cascade,
  place smallint not null,
  title text not null,
  color text,
  is_start boolean not null default false,
  -- [{ "field": "job_status", "value": "Surveying" }] applied when a record enters this level
  field_updates jsonb not null default '[]',
  allow_comments boolean not null default true,
  unique (workflow_id, place)
);

-- Who may act on records at this level ("recipients" in WebAuthor).
create table public.workflow_level_groups (
  level_id bigint not null references public.workflow_levels (id) on delete cascade,
  group_id smallint not null references public.groups (id) on delete cascade,
  primary key (level_id, group_id)
);

create table public.workflow_outcomes (
  id bigint generated by default as identity primary key,
  level_id bigint not null references public.workflow_levels (id) on delete cascade,
  place smallint not null,
  title text not null,
  -- goto: move to target_level_id · override: user picks any level · unsubmit: leave the workflow and unlock
  kind text not null default 'goto' check (kind in ('goto', 'override', 'unsubmit')),
  target_level_id bigint references public.workflow_levels (id) on delete cascade,
  check ((kind = 'goto') = (target_level_id is not null))
);

-- Where each record currently is.
create table public.record_workflow_state (
  table_name text not null,
  record_id bigint not null,
  workflow_id text not null references public.workflows (id),
  level_id bigint not null references public.workflow_levels (id),
  entered_at timestamptz not null default now(),
  entered_by uuid references public.profiles (id) on delete set null,
  primary key (table_name, record_id)
);
create index record_workflow_state_level_idx on public.record_workflow_state (level_id);

-- Timeline ("WF Timeline" in WebAuthor's Summary block).
create table public.workflow_events (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id bigint not null,
  workflow_id text not null references public.workflows (id),
  from_level_id bigint references public.workflow_levels (id),
  to_level_id bigint references public.workflow_levels (id),
  outcome text not null,
  comment text,
  actor uuid references public.profiles (id) on delete set null,
  at timestamptz not null default now()
);
create index workflow_events_record_idx on public.workflow_events (table_name, record_id, at desc);

-- ---------------------------------------------------------------- RLS: configuration readable; state/events via the record

alter table public.workflows enable row level security;
alter table public.workflow_levels enable row level security;
alter table public.workflow_level_groups enable row level security;
alter table public.workflow_outcomes enable row level security;
alter table public.record_workflow_state enable row level security;
alter table public.workflow_events enable row level security;

create policy "read" on public.workflows for select to authenticated using (true);
create policy "read" on public.workflow_levels for select to authenticated using (true);
create policy "read" on public.workflow_level_groups for select to authenticated using (true);
create policy "read" on public.workflow_outcomes for select to authenticated using (true);
create policy "read" on public.record_workflow_state for select to authenticated using (app.record_visible(table_name, record_id));
create policy "read" on public.workflow_events for select to authenticated using (app.record_visible(table_name, record_id));
-- No write policies: only the functions below change state.

create policy "admins manage" on public.workflows for all to authenticated using (app.is_sysadmin()) with check (app.is_sysadmin());
create policy "admins manage" on public.workflow_levels for all to authenticated using (app.is_sysadmin()) with check (app.is_sysadmin());
create policy "admins manage" on public.workflow_level_groups for all to authenticated using (app.is_sysadmin()) with check (app.is_sysadmin());
create policy "admins manage" on public.workflow_outcomes for all to authenticated using (app.is_sysadmin()) with check (app.is_sysadmin());

-- ---------------------------------------------------------------- engine

-- Workflow functions set this flag so the record write guard lets them update locked records.
create or replace function app.record_before_write()
returns trigger
language plpgsql security invoker set search_path = ''
as $$
declare
  uid uuid := auth.uid();
  engine boolean := coalesce(current_setting('app.engine', true), '') = 'on';
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    new.updated_at := now();
    if uid is not null then
      new.created_by := uid;
      new.updated_by := uid;
      if not engine then
        new.locked := false;
        new.submitted_at := null;
        new.archived_at := null;
        new.deleted_at := null;
      end if;
    end if;
    return new;
  end if;

  new.created_at := old.created_at;
  new.created_by := old.created_by;
  new.updated_at := now();
  if uid is not null then
    new.updated_by := uid;
  end if;
  if uid is null or engine then
    return new; -- engines are trusted
  end if;

  if not app.can_do(tg_table_name, 'modify')
     and (to_jsonb(new) - array['updated_at', 'updated_by', 'archived_at', 'deleted_at'])
         is distinct from (to_jsonb(old) - array['updated_at', 'updated_by', 'archived_at', 'deleted_at']) then
    raise exception 'You do not have permission to change % records', tg_table_name using errcode = '42501';
  end if;

  if new.deleted_at is distinct from old.deleted_at then
    if not app.can_do(tg_table_name, 'delete') then
      raise exception 'You do not have permission to delete % records', tg_table_name using errcode = '42501';
    end if;
    if old.locked and not app.can_lock_action(tg_table_name, 'delete_locked') then
      raise exception 'This record is locked' using errcode = '42501';
    end if;
  end if;

  if new.archived_at is distinct from old.archived_at and not app.can_do(tg_table_name, 'archive') then
    raise exception 'You do not have permission to archive % records', tg_table_name using errcode = '42501';
  end if;

  if new.locked is distinct from old.locked then
    if not (new.locked and new.submitted_at is not null and old.submitted_at is null)
       and not app.can_lock_action(tg_table_name, 'lock_unlock') then
      raise exception 'You do not have permission to lock or unlock records' using errcode = '42501';
    end if;
  elsif old.locked and new.deleted_at is not distinct from old.deleted_at
        and not app.can_lock_action(tg_table_name, 'modify_locked') then
    raise exception 'This record is locked' using errcode = '42501';
  end if;

  return new;
end;
$$;

-- Can the current user see this record (same test as the record table's view policy)?
create function app.user_can_see(p_table text, p_id bigint)
returns boolean
language plpgsql stable security definer set search_path = ''
as $$
declare
  creator uuid;
  found boolean;
begin
  execute format('select true, created_by from public.%I where id = $1 and deleted_at is null', p_table) into found, creator using p_id;
  if not coalesce(found, false) then
    return false;
  end if;
  return app.can_view_all(p_table) or (creator = auth.uid() and app.can_view_page(p_table));
end;
$$;

create function app.may_act_on_level(p_level bigint)
returns boolean
language sql stable security definer set search_path = ''
as $$
  select app.is_sysadmin() or exists (
    select 1 from public.workflow_level_groups lg
    join public.group_members gm on gm.group_id = lg.group_id and gm.user_id = auth.uid()
    join public.groups g on g.id = lg.group_id and g.active
    where lg.level_id = p_level
  );
$$;

-- Enter a level: apply its field updates (e.g. Job Status = Surveying) and record where the record is.
create function app.enter_level(p_table text, p_id bigint, p_workflow text, p_from bigint, p_to bigint, p_outcome text, p_comment text)
returns void
language plpgsql security definer set search_path = ''
as $$
declare
  u jsonb;
begin
  perform set_config('app.engine', 'on', true);
  for u in select * from jsonb_array_elements((select field_updates from public.workflow_levels where id = p_to)) loop
    execute format('update public.%I set %I = $1 where id = $2', p_table, u ->> 'field') using u ->> 'value', p_id;
  end loop;
  perform set_config('app.engine', 'off', true);

  insert into public.record_workflow_state (table_name, record_id, workflow_id, level_id, entered_at, entered_by)
  values (p_table, p_id, p_workflow, p_to, now(), auth.uid())
  on conflict (table_name, record_id) do update set level_id = excluded.level_id, entered_at = excluded.entered_at, entered_by = excluded.entered_by;

  insert into public.workflow_events (table_name, record_id, workflow_id, from_level_id, to_level_id, outcome, comment, actor)
  values (p_table, p_id, p_workflow, p_from, p_to, p_outcome, nullif(trim(p_comment), ''), auth.uid());
end;
$$;

/** Start the table's workflow for a record (on submit, or on create for Stock). */
create function public.workflow_start(p_table text, p_id bigint)
returns void
language plpgsql security definer set search_path = ''
as $$
declare
  wf public.workflows%rowtype;
  start_level bigint;
begin
  select * into wf from public.workflows where table_name = p_table and active;
  if not found then
    return; -- no workflow for this table
  end if;
  if not app.user_can_see(p_table, p_id) or not (app.can_do(p_table, 'modify') or app.can_do(p_table, 'create')) then
    raise exception 'You do not have permission to do that' using errcode = '42501';
  end if;
  if exists (select 1 from public.record_workflow_state where table_name = p_table and record_id = p_id) then
    return; -- already in the workflow
  end if;
  select id into start_level from public.workflow_levels where workflow_id = wf.id and is_start;
  perform app.enter_level(p_table, p_id, wf.id, null, start_level, 'Started', null);
end;
$$;

/** Take an outcome at the record's current level. p_target is used only by "Override". */
create function public.workflow_move(p_table text, p_id bigint, p_outcome bigint, p_target bigint default null, p_comment text default null)
returns void
language plpgsql security definer set search_path = ''
as $$
declare
  st public.record_workflow_state%rowtype;
  oc public.workflow_outcomes%rowtype;
  target bigint;
begin
  select * into st from public.record_workflow_state where table_name = p_table and record_id = p_id for update;
  if not found then
    raise exception 'This record is not in a workflow';
  end if;
  if not app.user_can_see(p_table, p_id) or not app.may_act_on_level(st.level_id) then
    raise exception 'You are not allowed to move this record at this stage' using errcode = '42501';
  end if;
  select * into oc from public.workflow_outcomes where id = p_outcome and level_id = st.level_id;
  if not found then
    raise exception 'That option is not available at this stage';
  end if;

  if oc.kind = 'unsubmit' then
    -- Leave the workflow: unlock and clear Date Submitted (trigger 725 then clears Job Status, M10).
    perform set_config('app.engine', 'on', true);
    execute format('update public.%I set locked = false, submitted_at = null where id = $1', p_table) using p_id;
    perform set_config('app.engine', 'off', true);
    delete from public.record_workflow_state where table_name = p_table and record_id = p_id;
    insert into public.workflow_events (table_name, record_id, workflow_id, from_level_id, to_level_id, outcome, comment, actor)
    values (p_table, p_id, st.workflow_id, st.level_id, null, oc.title, nullif(trim(p_comment), ''), auth.uid());
    return;
  end if;

  target := case when oc.kind = 'override' then p_target else oc.target_level_id end;
  if target is null or not exists (select 1 from public.workflow_levels where id = target and workflow_id = st.workflow_id) then
    raise exception 'Choose a stage to move to';
  end if;
  perform app.enter_level(p_table, p_id, st.workflow_id, st.level_id, target, oc.title, p_comment);
end;
$$;

/** "My Assigned": records at a level the current user may act on. */
create function public.my_workflow_queue()
returns table (table_name text, record_id bigint, workflow_id text, level_id bigint, level_title text, level_color text, entered_at timestamptz)
language sql stable security definer set search_path = ''
as $$
  select s.table_name, s.record_id, s.workflow_id, s.level_id, l.title, l.color, s.entered_at
  from public.record_workflow_state s
  join public.workflow_levels l on l.id = s.level_id
  join public.workflows w on w.id = s.workflow_id and w.active
  where app.may_act_on_level(s.level_id) and app.user_can_see(s.table_name, s.record_id)
  order by s.entered_at desc;
$$;

revoke execute on function public.workflow_start(text, bigint), public.workflow_move(text, bigint, bigint, bigint, text), public.my_workflow_queue() from public, anon;
grant execute on function public.workflow_start(text, bigint), public.workflow_move(text, bigint, bigint, bigint, text), public.my_workflow_queue() to authenticated;
revoke execute on function app.enter_level(text, bigint, text, bigint, bigint, text, text) from public, anon, authenticated;
grant execute on function app.user_can_see(text, bigint), app.may_act_on_level(bigint) to authenticated;
