-- F1 Scheduling (docs/portal-features-merge.md §A): visits on the calendar.
-- Same pattern as the M4 record tables (before_write / audit triggers, RLS via app.can_*).
-- Permissions (Fred 2026-09-30): office groups schedule; Technicians see the whole team schedule, read-only.

create table public.visits (
  id bigint generated by default as identity primary key,
  title text,
  project_id bigint references public.projects (id) on delete set null,
  starts_at timestamptz,
  duration text,
  arrival_window text,
  technician_id bigint references public.employees (id) on delete set null,
  service_type text,
  instructions text,
  access_notes text,
  status text,
  repeat text,
  repeat_count integer,
  series_id uuid,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.visits is 'Visits — scheduled work at a project (F1, not from WebAuthor)';
create index on public.visits (starts_at);
create index on public.visits (technician_id, starts_at);
create index on public.visits (project_id);
create index on public.visits (series_id);
create index on public.visits (created_by);
create index on public.visits (updated_at desc);

create table public.visits_team (
  record_id bigint not null references public.visits (id) on delete cascade,
  target_id bigint not null references public.employees (id) on delete cascade,
  primary key (record_id, target_id)
);
create index on public.visits_team (target_id);
comment on table public.visits_team is 'Visit › Also going';

insert into app.record_types (table_name, label, module, resource, parent_table, parent_column, lock_resource, sensitive_columns)
values ('visits', 'Visits', 'schedule', 'visits', null, null, null, '{}');

create trigger before_write before insert or update on public.visits for each row execute function app.record_before_write();
create trigger audit after insert or update on public.visits for each row execute function app.record_audit();

alter table public.visits enable row level security;
create policy "view" on public.visits for select to authenticated using ((select app.can_view_all('visits')) or (created_by = (select auth.uid()) and (select app.can_view_page('visits'))));
create policy "create" on public.visits for insert to authenticated with check ((select app.can_do('visits', 'create')));
create policy "modify" on public.visits for update to authenticated using (((select app.can_view_all('visits')) or (created_by = (select auth.uid()) and (select app.can_view_page('visits')))) and ((select app.can_do('visits', 'modify')) or (select app.can_do('visits', 'delete')) or (select app.can_do('visits', 'archive')))) with check (((select app.can_do('visits', 'modify')) or (select app.can_do('visits', 'delete')) or (select app.can_do('visits', 'archive'))));

alter table public.visits_team enable row level security;
create policy "view" on public.visits_team for select to authenticated using (exists (select 1 from public.visits r where r.id = record_id));
create policy "change" on public.visits_team for insert to authenticated with check (exists (select 1 from public.visits r where r.id = record_id) and (select app.can_do('visits', 'modify') or app.can_do('visits', 'create')));
create policy "remove" on public.visits_team for delete to authenticated using (exists (select 1 from public.visits r where r.id = record_id) and (select app.can_do('visits', 'modify')));

-- ---------------------------------------------------------------- permissions
insert into public.permissions (key, module, resource, action, kind, area, label, description) values
  ('schedule.visits.view_page', 'schedule', 'visits', 'view_page', 'page', 'Visits', 'Visits', 'See the Schedule and visits you created'),
  ('schedule.visits.view_all', 'schedule', 'visits', 'view_all', 'action', 'Visits', 'Visits: View All', 'See every visit (the whole team schedule)'),
  ('schedule.visits.create', 'schedule', 'visits', 'create', 'action', 'Visits', 'Visits: Add', 'Schedule new visits'),
  ('schedule.visits.modify', 'schedule', 'visits', 'modify', 'action', 'Visits', 'Visits: Modify', 'Change and move visits'),
  ('schedule.visits.delete', 'schedule', 'visits', 'delete', 'action', 'Visits', 'Visits: Delete', 'Delete visits (they can be restored)'),
  ('schedule.visits.archive', 'schedule', 'visits', 'archive', 'action', 'Visits', 'Visits: Archive', 'Archive and unarchive visits');

insert into public.group_permissions (group_id, permission_key)
select g.id, k
from public.groups g
cross join unnest(array['schedule.visits.view_page', 'schedule.visits.view_all', 'schedule.visits.create', 'schedule.visits.modify', 'schedule.visits.delete', 'schedule.visits.archive']) k
where g.slug in ('admin', 'office_management', 'coo', 'project_manager', 'treasurer');

insert into public.group_permissions (group_id, permission_key)
select g.id, k
from public.groups g
cross join unnest(array['schedule.visits.view_page', 'schedule.visits.view_all']) k
where g.slug = 'technician';
