-- M10: the 39 WebAuthor triggers (SPEC §5) with the decisions of SPEC §9.1:
--   Q7  closed date gaps (COI, permits, maintenance plans, driver's licences)
--   Q8  trigger 837 imported disabled
--   Q9  trigger 698 emails but no longer sets Status = "Expired"
--   Q14 trigger 735 (Saulo) now emails saulo@tsav.net
-- Conditions: "days" = today (US Eastern) − date, positive when the date is in the past.
-- Per-person conditions compare against WebAuthor employee ids (1000 Fred, 1002 Carlos, 1004 Jessica,
-- 1005 Luana, 1006 Lucas, 1012 Saulo, 1013 Ulisses); they match once employees are imported with their ids.

insert into public.automations (id, table_name, title, active, events, conditions, actions, notes) values
-- ---------------------------------------------------------------- Buildings
(694, 'buildings', 'Building COI Active', true, '{daily,added,modified,field:coi_expiration}',
  '{"match":"all","rules":[{"field":"coi_expiration","days":true,"op":"<","value":0}]}',
  '[{"type":"update","set":{"coi_status":"Active"}}]', 'Q7: active until the day before expiry'),
(695, 'buildings', 'Building COI Expired', true, '{daily,added,modified,field:coi_expiration}',
  '{"match":"all","rules":[{"field":"coi_expiration","days":true,"op":">=","value":0}]}',
  '[{"type":"update","set":{"coi_status":"Expired"}}]', null),

-- ---------------------------------------------------------------- Permits
(691, 'permits', 'Permit Active', true, '{daily,added,modified,field:expiration_date}',
  '{"match":"all","rules":[{"field":"expiration_date","days":true,"op":"<=","value":-31}]}',
  '[{"type":"update","set":{"expiration_status":"Active"}}]', null),
(693, 'permits', 'Permit Renew Alert', true, '{daily,added,field:expiration_date}',
  '{"match":"all","rules":[{"field":"expiration_date","days":true,"op":">=","value":-30},{"field":"expiration_date","days":true,"op":"<=","value":-1}]}',
  '[{"type":"update","set":{"expiration_status":"Renew Soon"}}]', 'Q7: −30…−1 (WebAuthor skipped −30)'),
(692, 'permits', 'Permit Expired', true, '{daily,added,modified,field:expiration_date}',
  '{"match":"all","rules":[{"field":"expiration_date","days":true,"op":">=","value":0}]}',
  '[{"type":"update","set":{"expiration_status":"Expired"}}]', null),
(696, 'permits', 'Permit Status Change Notification', true, '{field:status}',
  '{"match":"all","rules":[]}',
  '[{"type":"email","from":"info@tsav.net","to":["fred@tsav.net"],"subject":"Permit Status Changed","card":true,"link":true,"pdf":true}]', null),

-- ---------------------------------------------------------------- Projects
(837, 'projects', 'Auto Checklist from Reports', false, '{}',
  '{"match":"all","rules":[]}',
  '[{"type":"checklist","item":"{checklist}"}]', 'Q8: disabled — WebAuthor had no event and the {checklist} field does not exist'),
(708, 'projects', 'Current Status', true, '{hourly}',
  '{"match":"all","rules":[{"field":"invoiced_amount","op":"<=","field2":"paid_amount"},{"field":"financial_status","op":"!=","value":"Current"}]}',
  '[{"type":"update","set":{"financial_status":"Current"}}]', 'Empty amounts count as 0 (Q7)'),
(707, 'projects', 'Delinquent Status', true, '{hourly}',
  '{"match":"all","rules":[{"field":"invoiced_amount","op":">","field2":"paid_amount"},{"field":"financial_status","op":"!=","value":"Delinquent"}]}',
  '[{"type":"update","set":{"financial_status":"Delinquent"}}]', 'Empty amounts count as 0 (Q7)'),
(725, 'projects', 'Job Status on Unsubmit', true, '{field:submitted_at}',
  '{"match":"all","rules":[{"field":"submitted_at","op":"empty"}]}',
  '[{"type":"update","set":{"job_status":null}}]', null),
(689, 'projects', 'Maintenance Plan Active', true, '{daily,added,modified}',
  '{"match":"all","rules":[{"field":"maintenance_purchase_date","days":true,"op":"<","value":335}]}',
  '[{"type":"update","set":{"maintenance_status":"Active"}}]', 'Q7: < 335 days (WebAuthor < 334)'),
(686, 'projects', 'Maintenance Plan Renew', true, '{daily,added,field:maintenance_purchase_date}',
  '{"match":"all","rules":[{"field":"maintenance_purchase_date","days":true,"op":">=","value":335},{"field":"maintenance_purchase_date","days":true,"op":"<=","value":365}]}',
  '[{"type":"update","set":{"maintenance_status":"Renewal Alert"}}]', 'Q7: 335–365 days (WebAuthor 336–365)'),
(690, 'projects', 'Maintenance Plan Expired', true, '{daily,added,modified,field:maintenance_purchase_date}',
  '{"match":"all","rules":[{"field":"maintenance_purchase_date","days":true,"op":">","value":365}]}',
  '[{"type":"update","set":{"maintenance_status":"Expired"}}]', null),

-- ---------------------------------------------------------------- Punch List
(838, 'punch_list_items', 'Auto - Archive', true, '{field:status}',
  '{"match":"all","rules":[{"field":"status","op":"=","value":"Completed"}]}',
  '[{"type":"archive"}]', null),
(698, 'punch_list_items', 'Punch List Item Due', true, '{daily,added,modified,field:due_date}',
  '{"match":"any","rules":[{"field":"due_date","days":true,"op":"=","value":0},{"field":"due_date","days":true,"op":"=","value":7},{"field":"due_date","days":true,"op":"=","value":14},{"field":"due_date","days":true,"op":"=","value":30}]}',
  '[{"type":"email","from":"info@tsav.net","to":["info@tsav.net"],"subject":"Punch List item for {project_id} is Due Today","card":true,"link":true,"pdf":true}]',
  'Q9: no longer sets Status = "Expired" (not an option)'),
(730, 'punch_list_items', 'Punch List Notification for Carlos', true, '{added}',
  '{"match":"all","rules":[{"field":"team_member_id","op":"=","value":1002}]}',
  '[{"type":"email","from":"info@tsav.net","to":["carlosgurgel@tsmiami.com"],"subject":"Punch Item for {project_id} was added","card":true,"link":true}]', null),
(731, 'punch_list_items', 'Punch List Notification for Fred', true, '{added}',
  '{"match":"all","rules":[{"field":"team_member_id","op":"=","value":1000}]}',
  '[{"type":"email","from":"info@tsav.net","to":["fred@tsav.net"],"subject":"Punch Item for {project_id} was added","card":true,"link":true}]', null),
(732, 'punch_list_items', 'Punch List Notification for Jessica', true, '{added}',
  '{"match":"all","rules":[{"field":"team_member_id","op":"=","value":1004}]}',
  '[{"type":"email","from":"info@tsav.net","to":["jessica@tsav.net"],"subject":"Punch Item for {project_id} was added","card":true,"link":true}]', null),
(733, 'punch_list_items', 'Punch List Notification for Luana', true, '{added}',
  '{"match":"all","rules":[{"field":"team_member_id","op":"=","value":1005}]}',
  '[{"type":"email","from":"info@tsav.net","to":["luana@tsav.net"],"subject":"Punch Item for {project_id} was added","card":true,"link":true}]', null),
(734, 'punch_list_items', 'Punch List Notification for Lucas', true, '{added}',
  '{"match":"all","rules":[{"field":"team_member_id","op":"=","value":1006}]}',
  '[{"type":"email","from":"info@tsav.net","to":["lucas@tsav.net"],"subject":"Punch Item for {project_id} was added","card":true,"link":true}]', null),
(735, 'punch_list_items', 'Punch List Notification for Saulo', true, '{added}',
  '{"match":"all","rules":[{"field":"team_member_id","op":"=","value":1012}]}',
  '[{"type":"email","from":"saulo@tsav.net","to":["saulo@tsav.net"],"subject":"Punch Item for {project_id} was added","card":true,"link":true}]',
  'Q14: WebAuthor emailed lucas@tsav.net by mistake'),
(736, 'punch_list_items', 'Punch List Notification for Uli', true, '{added}',
  '{"match":"all","rules":[{"field":"team_member_id","op":"=","value":1013}]}',
  '[{"type":"email","from":"saulo@tsav.net","to":["uli@tsav.net"],"subject":"Punch Item for {project_id} was added","card":true,"link":true}]', null),

-- ---------------------------------------------------------------- Employees
(688, 'employees', 'Driver License Active', true, '{daily,added,modified,field:dl_expiration}',
  '{"match":"all","rules":[{"field":"dl_expiration","days":true,"op":"<=","value":0}]}',
  '[{"type":"update","set":{"dl_status":"Active"}}]', 'Q7: active through the expiry date'),
(687, 'employees', 'Update Driver License Status to Expired', true, '{daily,added,field:dl_expiration}',
  '{"match":"all","rules":[{"field":"dl_expiration","days":true,"op":">=","value":1}]}',
  '[{"type":"update","set":{"dl_status":"Expired"}}]', 'Q7: expired only once the date has passed'),

-- ---------------------------------------------------------------- Tasks
(700, 'tasks', 'Change Status to DUE upon date expiration', true, '{daily,modified,field:due_date}',
  '{"match":"all","rules":[{"field":"due_date","days":true,"op":">=","value":0}]}',
  '[{"type":"update","set":{"due_status":"Due"}}]', null),
(705, 'tasks', 'Email Carlos on a new or due task', true, '{added,field:status}',
  '{"match":"all","rules":[{"field":"member_id","op":"=","value":1002}]}',
  '[{"type":"email","from":"info@tsav.net","to":["carlosgurgel@tsmiami.com"],"subject":"Task Added or Due","card":true,"link":true,"pdf":true}]', null),
(699, 'tasks', 'Email Fred on a new or due task', true, '{added,field:status}',
  '{"match":"all","rules":[{"field":"member_id","op":"=","value":1000}]}',
  '[{"type":"email","from":"info@tsav.net","to":["fred@tsav.net"],"subject":"Task Added or Due","card":true,"link":true,"pdf":true}]', null),
(701, 'tasks', 'Email Jessica on a new or due task', true, '{added,field:status}',
  '{"match":"all","rules":[{"field":"member_id","op":"=","value":1004}]}',
  '[{"type":"email","from":"info@tsav.net","to":["jessica@tsav.net"],"subject":"Task Added or Due","card":true,"link":true,"pdf":true}]', null),
(702, 'tasks', 'Email Luana on a new or due task', true, '{added,field:status}',
  '{"match":"all","rules":[{"field":"member_id","op":"=","value":1005}]}',
  '[{"type":"email","from":"info@tsav.net","to":["luana@tsav.net"],"subject":"Task Added or Due","card":true,"link":true,"pdf":true}]', null),
(706, 'tasks', 'Email Lucas on a new or due task', true, '{added,field:status}',
  '{"match":"all","rules":[{"field":"member_id","op":"=","value":1006}]}',
  '[{"type":"email","from":"info@tsav.net","to":["lucas@tsav.net"],"subject":"Task Added or Due","card":true,"link":true,"pdf":true}]', null),
(704, 'tasks', 'Email Saulo on a new or due task', true, '{added,field:status}',
  '{"match":"all","rules":[{"field":"member_id","op":"=","value":1012}]}',
  '[{"type":"email","from":"info@tsav.net","to":["saulo@tsav.net"],"subject":"Task Added or Due","card":true,"link":true,"pdf":true}]', null),
(703, 'tasks', 'Email Ulisses on a new or due task', true, '{added,field:status}',
  '{"match":"all","rules":[{"field":"member_id","op":"=","value":1013}]}',
  '[{"type":"email","from":"info@tsav.net","to":["uli@tsav.net"],"subject":"Task Added or Due","card":true,"link":true,"pdf":true}]', null),

-- ---------------------------------------------------------------- Job Report
(839, 'job_reports', 'SEND EMAIL FOR EVERY REPORT', true, '{added}',
  '{"match":"all","rules":[]}',
  '[{"type":"email","from":"TS CRM","to":["techsquadreports@gmail.com"],"subject":"{project_id} ( {team_ids}) -  {date}","card":true,"pdf":true,"files":["files"]}]', null),
(856, 'job_reports', 'Update Checklist Field 1', true, '{added}',
  '{"match":"all","rules":[{"field":"pending_1","op":"not_empty"}]}',
  '[{"type":"checklist","target":"project_id","item":"{pending_1}"}]', null),
(860, 'job_reports', 'Update Checklist Field 2', true, '{added}',
  '{"match":"all","rules":[{"field":"pending_2","op":"not_empty"}]}',
  '[{"type":"checklist","target":"project_id","item":"{pending_2}"}]', null),
(861, 'job_reports', 'Update Checklist Field 3', true, '{added}',
  '{"match":"all","rules":[{"field":"pending_3","op":"not_empty"}]}',
  '[{"type":"checklist","target":"project_id","item":"{pending_3}"}]', null),
(862, 'job_reports', 'Update Checklist Field 4', true, '{added}',
  '{"match":"all","rules":[{"field":"pending_4","op":"not_empty"}]}',
  '[{"type":"checklist","target":"project_id","item":"{pending_4}"}]', null),
(863, 'job_reports', 'Update Checklist Field 5', true, '{added}',
  '{"match":"all","rules":[{"field":"pending_5","op":"not_empty"}]}',
  '[{"type":"checklist","target":"project_id","item":"{pending_5}"}]', null),

-- ---------------------------------------------------------------- TV Installation
(713, 'tv_installations', 'Email Copy of Form to Signer', true, '{added}',
  '{"match":"all","rules":[]}',
  '[{"type":"email","from":"TS CRM","to":["{email}"],"bcc":["techsquadreports@gmail.com"],"subject":" Installation and Condition Form {project_id} {room_area} {brand_and_model}","pdf":true,"files":["pictures"]}]', null);
