-- GENERATED by scripts/generate-schema.ts from src/registry (M4). Do not edit by hand;
-- once applied, change the schema with a new migration.

-- Projects (WebAuthor fx_techsquad_projects)
create table public.projects (
  id bigint generated by default as identity primary key,
  job_status text,
  title text,
  type text,
  category text,
  job_owner_id bigint,
  job_address jsonb,
  owner_contact text,
  owner_contact_intl text,
  door_gate_code text,
  in_building boolean not null default false,
  building_id bigint,
  apartment_or_unit text,
  has_permit boolean not null default false,
  permit_id bigint,
  has_designer boolean not null default false,
  design_firm_id bigint,
  lead_designer_id bigint,
  designer_notes text,
  has_general_contractor boolean not null default false,
  general_contractor_id bigint,
  gc_pm_id bigint,
  general_contractor_notes text,
  has_builder_developer boolean not null default false,
  builder_developer_id bigint,
  builder_developer_notes text,
  referral_type text default 'None',
  referral_contact_id bigint,
  referral_organization_id bigint,
  commission_notes text,
  survey_videos_links text,
  plans text,
  financial_status text,
  warranty boolean not null default false,
  start_date date,
  maintenance_plan boolean not null default false,
  maintenance_type text,
  maintenance_status text,
  maintenance_purchase_date date,
  maintenance_sales_person_id bigint,
  maintenance_amount numeric(12,2),
  maintenance_history text,
  special_orders boolean not null default false,
  list_items text,
  older_reports text,
  system_credentials text,
  systems text[] not null default '{}',
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.projects is 'Projects — WebAuthor fx_techsquad_projects';
comment on column public.projects.job_status is 'Job Status';
comment on column public.projects.title is 'Project Name';
comment on column public.projects.type is 'Type';
comment on column public.projects.category is 'Category';
comment on column public.projects.job_owner_id is 'Job Owner';
comment on column public.projects.job_address is 'Job Address';
comment on column public.projects.owner_contact is 'Owner Contact';
comment on column public.projects.owner_contact_intl is 'Owner Contact Intl';
comment on column public.projects.door_gate_code is 'Door / Gate Code';
comment on column public.projects.in_building is 'Building or Development';
comment on column public.projects.building_id is 'Building / Development';
comment on column public.projects.apartment_or_unit is 'Apartment or Unit #';
comment on column public.projects.has_permit is 'Permit';
comment on column public.projects.permit_id is 'Choose Permit';
comment on column public.projects.has_designer is 'Designer';
comment on column public.projects.design_firm_id is 'Design Firm';
comment on column public.projects.lead_designer_id is 'Lead Designer';
comment on column public.projects.designer_notes is 'Designer Notes';
comment on column public.projects.has_general_contractor is 'General Contractor';
comment on column public.projects.general_contractor_id is 'General Contractor';
comment on column public.projects.gc_pm_id is 'GC PM';
comment on column public.projects.general_contractor_notes is 'GC Notes';
comment on column public.projects.has_builder_developer is 'Builder or Developer';
comment on column public.projects.builder_developer_id is 'Builder / Developer';
comment on column public.projects.builder_developer_notes is 'Builder / Developer Notes';
comment on column public.projects.referral_type is 'Referral';
comment on column public.projects.referral_contact_id is 'Person';
comment on column public.projects.referral_organization_id is 'Organization';
comment on column public.projects.commission_notes is 'Commission Notes';
comment on column public.projects.survey_videos_links is 'Survey Videos Links';
comment on column public.projects.plans is 'Plans';
comment on column public.projects.financial_status is 'Financial Status';
comment on column public.projects.warranty is 'Warranty';
comment on column public.projects.start_date is 'Start Date';
comment on column public.projects.maintenance_plan is 'Maintenance Plan';
comment on column public.projects.maintenance_type is 'Type';
comment on column public.projects.maintenance_status is 'Status';
comment on column public.projects.maintenance_purchase_date is 'Purchase Date';
comment on column public.projects.maintenance_sales_person_id is 'Sales Person';
comment on column public.projects.maintenance_amount is 'Amount';
comment on column public.projects.maintenance_history is 'History';
comment on column public.projects.special_orders is 'Special Orders';
comment on column public.projects.list_items is 'List Items';
comment on column public.projects.older_reports is 'Reports and Pictures Section';
comment on column public.projects.system_credentials is 'System Credentials (sensitive: stored encrypted by the app)';
comment on column public.projects.systems is 'Systems';

-- Contacts (WebAuthor fx_techsquad_projects_xmcontacts)
create table public.contacts (
  id bigint generated by default as identity primary key,
  title text,
  type text default 'End Customer',
  first_name text,
  last_name text,
  organization_id bigint,
  role_position text,
  alias_dba text,
  address jsonb,
  main_phone text,
  phone_extension text,
  intl_phone text,
  email text,
  has_alternate_contact boolean not null default false,
  alternate_name text,
  alternate_role_title text,
  alternate_intl_phone text,
  alternate_phone text,
  alternate_email text,
  preferred_language text,
  notes text,
  was_referred boolean not null default false,
  referred_by_organization_id bigint,
  referred_by_contact_id bigint,
  referred_by_employee_id bigint,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.contacts is 'Contacts — WebAuthor fx_techsquad_projects_xmcontacts';
comment on column public.contacts.title is 'Title';
comment on column public.contacts.type is 'Type';
comment on column public.contacts.first_name is 'First Name';
comment on column public.contacts.last_name is 'Last Name';
comment on column public.contacts.organization_id is 'Organization Name';
comment on column public.contacts.role_position is 'Role / Position';
comment on column public.contacts.alias_dba is 'Alias / DBA';
comment on column public.contacts.address is 'Address';
comment on column public.contacts.main_phone is 'Main Phone';
comment on column public.contacts.phone_extension is 'Phone Ext';
comment on column public.contacts.intl_phone is 'Intl Phone';
comment on column public.contacts.email is 'Email';
comment on column public.contacts.has_alternate_contact is 'Alternate Contact ?';
comment on column public.contacts.alternate_name is 'Alternate Name';
comment on column public.contacts.alternate_role_title is 'Alternate Role / Tilte';
comment on column public.contacts.alternate_intl_phone is 'Alternate Intl Phone';
comment on column public.contacts.alternate_phone is 'Alternate Phone';
comment on column public.contacts.alternate_email is 'Alternate Email';
comment on column public.contacts.preferred_language is 'Preferred Language';
comment on column public.contacts.notes is 'Notes';
comment on column public.contacts.was_referred is 'Referred by anyone?';
comment on column public.contacts.referred_by_organization_id is 'Organization';
comment on column public.contacts.referred_by_contact_id is 'Person';
comment on column public.contacts.referred_by_employee_id is 'Employee';

-- Interactions (WebAuthor fx_techsquad_projects_xmcontacts_interactions)
create table public.contact_interactions (
  id bigint generated by default as identity primary key,
  contact_id bigint not null,
  title text default '0',
  type text,
  date date default ((now() at time zone 'America/New_York')::date),
  result text,
  follow_up_date date,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.contact_interactions is 'Interactions — WebAuthor fx_techsquad_projects_xmcontacts_interactions';
comment on column public.contact_interactions.contact_id is 'Contacts';
comment on column public.contact_interactions.title is 'Title';
comment on column public.contact_interactions.type is 'Type';
comment on column public.contact_interactions.date is 'Date';
comment on column public.contact_interactions.result is 'Result';
comment on column public.contact_interactions.follow_up_date is 'Follow Up Date';

-- Buildings / Developments (WebAuthor fx_techsquad_projects_xmbuildings)
create table public.buildings (
  id bigint generated by default as identity primary key,
  title text,
  address jsonb,
  work_hours text,
  details text,
  website text,
  coi_expiration date,
  coi_status text,
  admin_name text,
  admin_phone text,
  admin_email text,
  receiving_agent text,
  receiving_phone text,
  receiving_email text,
  front_desk_contact text,
  front_desk_phone text,
  front_desk_email text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.buildings is 'Buildings / Developments — WebAuthor fx_techsquad_projects_xmbuildings';
comment on column public.buildings.title is 'Building / Developement';
comment on column public.buildings.address is 'Address';
comment on column public.buildings.work_hours is 'Work Hours';
comment on column public.buildings.details is 'Details';
comment on column public.buildings.website is 'Website';
comment on column public.buildings.coi_expiration is 'COI Expiration';
comment on column public.buildings.coi_status is 'COI Status';
comment on column public.buildings.admin_name is 'Building Admin';
comment on column public.buildings.admin_phone is 'Admin Phone';
comment on column public.buildings.admin_email is 'Email';
comment on column public.buildings.receiving_agent is 'Receiving Agent';
comment on column public.buildings.receiving_phone is 'Receiving Phone';
comment on column public.buildings.receiving_email is 'Email';
comment on column public.buildings.front_desk_contact is 'Contact';
comment on column public.buildings.front_desk_phone is 'Front Desk Phone';
comment on column public.buildings.front_desk_email is 'Email';

-- Permits (WebAuthor fx_techsquad_projects_xmpermits)
create table public.permits (
  id bigint generated by default as identity primary key,
  title text,
  municipality_id bigint,
  type text,
  project_id bigint,
  address jsonb,
  owner_contact_id bigint,
  owner_phone text,
  status text,
  el_permit_number text,
  master_permit_number text,
  expiration_date date,
  expiration_status text,
  notes text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.permits is 'Permits — WebAuthor fx_techsquad_projects_xmpermits';
comment on column public.permits.title is 'Title';
comment on column public.permits.municipality_id is 'Municipality';
comment on column public.permits.type is 'Type';
comment on column public.permits.project_id is 'Project';
comment on column public.permits.address is 'Address';
comment on column public.permits.owner_contact_id is 'Owner Name';
comment on column public.permits.owner_phone is 'Owner Phone Number';
comment on column public.permits.status is 'Status';
comment on column public.permits.el_permit_number is 'EL Permit Number';
comment on column public.permits.master_permit_number is 'Master Permit Number';
comment on column public.permits.expiration_date is 'Permit Expiration Date';
comment on column public.permits.expiration_status is 'Permit Expiration';
comment on column public.permits.notes is 'Notes';

-- Organizations (WebAuthor fx_techsquad_projects_xmorganizations)
create table public.organizations (
  id bigint generated by default as identity primary key,
  title text,
  type text,
  dba_or_legal_name text,
  address jsonb,
  main_phone text,
  main_email text,
  default_commission_markup text,
  tax_exempt boolean not null default false,
  dealer_number text,
  coi_expiration date,
  website text,
  portal_login text,
  portal_password text,
  details text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.organizations is 'Organizations — WebAuthor fx_techsquad_projects_xmorganizations';
comment on column public.organizations.title is 'Organization Name';
comment on column public.organizations.type is 'Type';
comment on column public.organizations.dba_or_legal_name is 'DBA ( or Legal name )';
comment on column public.organizations.address is 'Address';
comment on column public.organizations.main_phone is 'Main Phone';
comment on column public.organizations.main_email is 'Main Email';
comment on column public.organizations.default_commission_markup is 'Default Commission / Markup';
comment on column public.organizations.tax_exempt is 'Tax Exempt ?';
comment on column public.organizations.dealer_number is 'Dealer Number';
comment on column public.organizations.coi_expiration is 'COI Expiration';
comment on column public.organizations.website is 'Website';
comment on column public.organizations.portal_login is 'Login';
comment on column public.organizations.portal_password is 'Password (sensitive: stored encrypted by the app)';
comment on column public.organizations.details is 'Details';

-- Punch List (WebAuthor fx_techsquad_projects_xmpunch_list)
create table public.punch_list_items (
  id bigint generated by default as identity primary key,
  title text,
  project_id bigint,
  type text,
  team_member_id bigint,
  details text,
  priority text,
  due_date date,
  status text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.punch_list_items is 'Punch List — WebAuthor fx_techsquad_projects_xmpunch_list';
comment on column public.punch_list_items.title is 'Created';
comment on column public.punch_list_items.project_id is 'Project';
comment on column public.punch_list_items.type is 'Type';
comment on column public.punch_list_items.team_member_id is 'Team';
comment on column public.punch_list_items.details is 'Details';
comment on column public.punch_list_items.priority is 'Priority';
comment on column public.punch_list_items.due_date is 'Due Date';
comment on column public.punch_list_items.status is 'Status';

-- Employees (WebAuthor fx_techsquad_employee)
create table public.employees (
  id bigint generated by default as identity primary key,
  title text,
  first_name text,
  last_name text,
  departments text[] not null default '{}',
  status text,
  date_of_birth date,
  home_address jsonb,
  email text,
  phone text,
  dl_expiration date,
  dl_status text,
  employment_type text,
  ssn text,
  company_name text,
  ein text,
  workers_comp_expiration date,
  start_date date,
  termination_date date,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.employees is 'Employees — WebAuthor fx_techsquad_employee';
comment on column public.employees.title is 'Title';
comment on column public.employees.first_name is 'First Name';
comment on column public.employees.last_name is 'Last Name';
comment on column public.employees.departments is 'Department';
comment on column public.employees.status is 'Status';
comment on column public.employees.date_of_birth is 'Date of Birth';
comment on column public.employees.home_address is 'Home Address';
comment on column public.employees.email is 'Email';
comment on column public.employees.phone is 'Phone Number';
comment on column public.employees.dl_expiration is 'D/L Expiration';
comment on column public.employees.dl_status is 'D/L Status';
comment on column public.employees.employment_type is 'Type';
comment on column public.employees.ssn is 'Social Security Number (sensitive: stored encrypted by the app)';
comment on column public.employees.company_name is 'Company Name';
comment on column public.employees.ein is 'EIN#';
comment on column public.employees.workers_comp_expiration is 'Workers'' Comp Exemption Expiration';
comment on column public.employees.start_date is 'Effective Start Date';
comment on column public.employees.termination_date is 'Termination Date';

-- Fleet (WebAuthor fx_techsquad_employee_xmfleet)
create table public.vehicles (
  id bigint generated by default as identity primary key,
  title text,
  populate_on_reports text,
  year integer,
  make_and_model text,
  tag_number text,
  vin text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.vehicles is 'Fleet — WebAuthor fx_techsquad_employee_xmfleet';
comment on column public.vehicles.populate_on_reports is 'Populate on Reports';
comment on column public.vehicles.year is 'Year';
comment on column public.vehicles.make_and_model is 'Make and Model';
comment on column public.vehicles.tag_number is 'Tag #';
comment on column public.vehicles.vin is 'VIN#';

-- Tasks (WebAuthor fx_techsquad_employee_xmtasks)
create table public.tasks (
  id bigint generated by default as identity primary key,
  title text,
  member_id bigint,
  status text,
  details text,
  due_date date,
  priority text,
  due_status text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.tasks is 'Tasks — WebAuthor fx_techsquad_employee_xmtasks';
comment on column public.tasks.title is 'Date Created';
comment on column public.tasks.member_id is 'Member';
comment on column public.tasks.status is 'Status';
comment on column public.tasks.details is 'Details';
comment on column public.tasks.due_date is 'Due Date';
comment on column public.tasks.priority is 'Priority';
comment on column public.tasks.due_status is 'Status';

-- RMA (WebAuthor fx_techsquad_employee_xmrma)
create table public.rmas (
  id bigint generated by default as identity primary key,
  title text,
  project_id bigint,
  manufacturer_id bigint,
  equipment text,
  serial_numbers text,
  date_submitted date default ((now() at time zone 'America/New_York')::date),
  rma_number text,
  details text,
  status text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.rmas is 'RMA — WebAuthor fx_techsquad_employee_xmrma';
comment on column public.rmas.title is 'Title';
comment on column public.rmas.project_id is 'Client';
comment on column public.rmas.manufacturer_id is 'Manufacturer';
comment on column public.rmas.equipment is 'Equipment Description or Model #';
comment on column public.rmas.serial_numbers is 'Serial Number (s)';
comment on column public.rmas.date_submitted is 'Date Submitted';
comment on column public.rmas.rma_number is 'RMA Number';
comment on column public.rmas.details is 'Details';
comment on column public.rmas.status is 'Status';

-- Transactions (WebAuthor fx_techsquad_employee_xmpayins)
create table public.transactions (
  id bigint generated by default as identity primary key,
  title text,
  payment_type text,
  project_id bigint,
  type text,
  contact_id bigint,
  organization_id bigint,
  reason text,
  description text,
  portal_number text,
  amount numeric(12,2),
  date date default ((now() at time zone 'America/New_York')::date),
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.transactions is 'Transactions — WebAuthor fx_techsquad_employee_xmpayins';
comment on column public.transactions.title is 'Title';
comment on column public.transactions.payment_type is 'Payment Type';
comment on column public.transactions.project_id is 'Apply to Project';
comment on column public.transactions.type is 'Type';
comment on column public.transactions.contact_id is 'Pay Individual';
comment on column public.transactions.organization_id is 'Pay Organization';
comment on column public.transactions.reason is 'Reason';
comment on column public.transactions.description is 'Description';
comment on column public.transactions.portal_number is 'Portal Proposal or Invoice #';
comment on column public.transactions.amount is 'Amount';
comment on column public.transactions.date is 'Date';

-- Inventory Checkout (WebAuthor fx_techsquad_employee_xminventory_checkout)
create table public.inventory_checkouts (
  id bigint generated by default as identity primary key,
  title text,
  type text default 'Materials',
  project_id bigint,
  technician_id bigint,
  date date default ((now() at time zone 'America/New_York')::date),
  equipment text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.inventory_checkouts is 'Inventory Checkout — WebAuthor fx_techsquad_employee_xminventory_checkout';
comment on column public.inventory_checkouts.type is 'Type';
comment on column public.inventory_checkouts.project_id is 'Project';
comment on column public.inventory_checkouts.technician_id is 'Technician';
comment on column public.inventory_checkouts.date is 'Date';
comment on column public.inventory_checkouts.equipment is 'Equipment';

-- Payroll (WebAuthor fx_techsquad_employee_xmpayouts)
create table public.payouts (
  id bigint generated by default as identity primary key,
  title text,
  employee_id bigint,
  reason text,
  amount numeric(12,2),
  date_issued date default ((now() at time zone 'America/New_York')::date),
  payment_method text,
  check_number integer,
  details text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.payouts is 'Payroll — WebAuthor fx_techsquad_employee_xmpayouts';
comment on column public.payouts.title is 'Title';
comment on column public.payouts.employee_id is 'Employee';
comment on column public.payouts.reason is 'Reason';
comment on column public.payouts.amount is 'Amount';
comment on column public.payouts.date_issued is 'Date Issued';
comment on column public.payouts.payment_method is 'Method of payment';
comment on column public.payouts.check_number is 'Check Number';
comment on column public.payouts.details is 'Details ( Optional )';

-- Products (WebAuthor fx_techsquad_inventory)
create table public.products (
  id bigint generated by default as identity primary key,
  title text,
  product_type text,
  supplier_id bigint,
  brand_id bigint,
  sku text,
  model text,
  sell_price numeric(12,2),
  cost numeric(12,2),
  location text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.products is 'Products — WebAuthor fx_techsquad_inventory';
comment on column public.products.title is 'Title';
comment on column public.products.product_type is 'Product Type';
comment on column public.products.supplier_id is 'Supplier';
comment on column public.products.brand_id is 'Brand';
comment on column public.products.sku is 'SKU';
comment on column public.products.model is 'Model';
comment on column public.products.sell_price is 'Sell Price';
comment on column public.products.cost is 'Cost';
comment on column public.products.location is 'Location';

-- Sale (WebAuthor fx_techsquad_inventory_xmsale)
create table public.sales (
  id bigint generated by default as identity primary key,
  title text,
  stock_item_id bigint,
  mac_address text,
  product_type text,
  brand_id bigint,
  model text,
  sell_price numeric(12,2),
  cost numeric(12,2),
  destination_project_id bigint,
  staff_id bigint,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.sales is 'Sale — WebAuthor fx_techsquad_inventory_xmsale';
comment on column public.sales.title is 'Title';
comment on column public.sales.stock_item_id is 'Serial';
comment on column public.sales.mac_address is 'MAC';
comment on column public.sales.product_type is 'Product Type';
comment on column public.sales.brand_id is 'Brand';
comment on column public.sales.model is 'Model';
comment on column public.sales.sell_price is 'Sell Price';
comment on column public.sales.cost is 'Cost';
comment on column public.sales.destination_project_id is 'Destination';
comment on column public.sales.staff_id is 'Staff';

-- Stock (WebAuthor fx_techsquad_inventory_xmstock)
create table public.stock_items (
  id bigint generated by default as identity primary key,
  title text,
  product_id bigint,
  serial text,
  mac_address text,
  location text,
  product_type text,
  brand_id bigint,
  model text,
  sell_price numeric(12,2),
  cost numeric(12,2),
  destination_project_id bigint,
  staff_id bigint,
  status text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.stock_items is 'Stock — WebAuthor fx_techsquad_inventory_xmstock';
comment on column public.stock_items.product_id is 'SKU';
comment on column public.stock_items.serial is 'Serial';
comment on column public.stock_items.mac_address is 'MAC';
comment on column public.stock_items.location is 'Location';
comment on column public.stock_items.product_type is 'Product Type';
comment on column public.stock_items.brand_id is 'Brand';
comment on column public.stock_items.model is 'Model';
comment on column public.stock_items.sell_price is 'Sell Price';
comment on column public.stock_items.cost is 'Cost';
comment on column public.stock_items.destination_project_id is 'Destination';
comment on column public.stock_items.staff_id is 'Staff';
comment on column public.stock_items.status is 'Status';

-- Support Tickets (WebAuthor fx_techsquad_help_desk)
create table public.support_tickets (
  id bigint generated by default as identity primary key,
  title text,
  issue_description text,
  priority text,
  only_me text default '1',
  status text,
  assigned_to uuid references public.profiles (id) on delete set null,
  issue_category text,
  date_closed date,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.support_tickets is 'Support Tickets — WebAuthor fx_techsquad_help_desk';
comment on column public.support_tickets.title is 'Title';
comment on column public.support_tickets.issue_description is 'Issue Description';
comment on column public.support_tickets.priority is 'Priority Level';
comment on column public.support_tickets.only_me is 'Are you the only one with this issue?';
comment on column public.support_tickets.status is 'Status';
comment on column public.support_tickets.assigned_to is 'Assigned To';
comment on column public.support_tickets.issue_category is 'Issue Category';
comment on column public.support_tickets.date_closed is 'Date Closed';

-- Support Notes (WebAuthor fx_techsquad_help_desk_support_note)
create table public.support_notes (
  id bigint generated by default as identity primary key,
  title text,
  ticket_id bigint not null,
  assigned_to uuid references public.profiles (id) on delete set null,
  note_date date default ((now() at time zone 'America/New_York')::date),
  note text,
  issue_category text,
  status text,
  closed_date date default ((now() at time zone 'America/New_York')::date),
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.support_notes is 'Support Notes — WebAuthor fx_techsquad_help_desk_support_note';
comment on column public.support_notes.ticket_id is 'Support Tickets';
comment on column public.support_notes.assigned_to is 'Assigned to';
comment on column public.support_notes.note_date is 'Note Date';
comment on column public.support_notes.note is 'Note';
comment on column public.support_notes.issue_category is 'Issue Category';
comment on column public.support_notes.status is 'Status';
comment on column public.support_notes.closed_date is 'Closed Date';

-- Articles (WebAuthor fx_techsquad_help_desk_xmarticles)
create table public.kb_articles (
  id bigint generated by default as identity primary key,
  title text,
  category_id bigint,
  status text,
  updated_on date default ((now() at time zone 'America/New_York')::date),
  video_link text,
  content text,
  view_count integer,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.kb_articles is 'Articles — WebAuthor fx_techsquad_help_desk_xmarticles';
comment on column public.kb_articles.title is 'Title';
comment on column public.kb_articles.category_id is 'Category';
comment on column public.kb_articles.status is 'Status';
comment on column public.kb_articles.updated_on is 'Date of Update';
comment on column public.kb_articles.video_link is 'Video Link';
comment on column public.kb_articles.content is 'Content';
comment on column public.kb_articles.view_count is 'View Count';

-- Suppliers (WebAuthor fx_techsquad_util_supplier)
create table public.suppliers (
  id bigint generated by default as identity primary key,
  title text,
  name text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.suppliers is 'Suppliers — WebAuthor fx_techsquad_util_supplier';
comment on column public.suppliers.title is 'Title';
comment on column public.suppliers.name is 'Company Name';

-- Brands (WebAuthor fx_techsquad_util_brand)
create table public.brands (
  id bigint generated by default as identity primary key,
  title text,
  name text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.brands is 'Brands — WebAuthor fx_techsquad_util_brand';
comment on column public.brands.title is 'Title';
comment on column public.brands.name is 'Brand';

-- Knowledge Base Categories (WebAuthor fx_techsquad_util_knowledge_base_category)
create table public.kb_categories (
  id bigint generated by default as identity primary key,
  title text,
  icon_class text,
  sort_order integer,
  active boolean not null default true,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.kb_categories is 'Knowledge Base Categories — WebAuthor fx_techsquad_util_knowledge_base_category';
comment on column public.kb_categories.title is 'Title';
comment on column public.kb_categories.icon_class is 'Icon Class';
comment on column public.kb_categories.sort_order is 'Place';
comment on column public.kb_categories.active is 'Active';

-- Job Report (WebAuthor frx_techsquad_job_report)
create table public.job_reports (
  id bigint generated by default as identity primary key,
  title text,
  project_id bigint,
  date date default ((now() at time zone 'America/New_York')::date),
  vehicle_id bigint,
  report text,
  pending_1 text,
  pending_2 text,
  pending_3 text,
  pending_4 text,
  pending_5 text,
  logins_and_passwords text,
  maintenance_plan_service_call boolean not null default false,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.job_reports is 'Job Report — WebAuthor frx_techsquad_job_report';
comment on column public.job_reports.title is 'Title';
comment on column public.job_reports.project_id is 'Project';
comment on column public.job_reports.date is 'Date';
comment on column public.job_reports.vehicle_id is 'Vehicle';
comment on column public.job_reports.report is 'Report';
comment on column public.job_reports.pending_1 is '1 - Pending';
comment on column public.job_reports.pending_2 is '2 - Pending';
comment on column public.job_reports.pending_3 is '3 - Pending';
comment on column public.job_reports.pending_4 is '4 - Pending';
comment on column public.job_reports.pending_5 is '5 - Pending';
comment on column public.job_reports.logins_and_passwords is 'Login and Passwords (sensitive: stored encrypted by the app)';
comment on column public.job_reports.maintenance_plan_service_call is 'Maintenance Plan Service Call ?';

-- Note (WebAuthor frx_techsquad_note)
create table public.form_notes (
  id bigint generated by default as identity primary key,
  title text,
  project_id bigint,
  note_type text,
  description text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.form_notes is 'Note — WebAuthor frx_techsquad_note';
comment on column public.form_notes.title is 'Title';
comment on column public.form_notes.project_id is 'Project';
comment on column public.form_notes.note_type is 'Type of Note';
comment on column public.form_notes.description is 'Description';

-- Staff Performance (WebAuthor frx_techsquad_staff_performance)
create table public.staff_performance (
  id bigint generated by default as identity primary key,
  title text,
  employee_id bigint,
  date date,
  type text,
  description text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.staff_performance is 'Staff Performance — WebAuthor frx_techsquad_staff_performance';
comment on column public.staff_performance.title is 'Title';
comment on column public.staff_performance.employee_id is 'Staff Member';
comment on column public.staff_performance.date is 'Date';
comment on column public.staff_performance.type is 'Type';
comment on column public.staff_performance.description is 'Description';

-- Survey and Proposals (WebAuthor frx_techsquad_survey_and_proposals)
create table public.survey_proposals (
  id bigint generated by default as identity primary key,
  title text,
  project_id bigint,
  survey_details text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.survey_proposals is 'Survey and Proposals — WebAuthor frx_techsquad_survey_and_proposals';
comment on column public.survey_proposals.title is 'Title';
comment on column public.survey_proposals.project_id is 'Project';
comment on column public.survey_proposals.survey_details is 'Survey Details';

-- TV Installation (WebAuthor frx_techsquad_tv_installation)
create table public.tv_installations (
  id bigint generated by default as identity primary key,
  title text,
  date date default ((now() at time zone 'America/New_York')::date),
  project_id bigint,
  room_area text,
  brand_and_model text,
  serial_number text,
  validated_by text,
  email text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.tv_installations is 'TV Installation — WebAuthor frx_techsquad_tv_installation';
comment on column public.tv_installations.title is 'Title';
comment on column public.tv_installations.date is 'Date';
comment on column public.tv_installations.project_id is 'Project';
comment on column public.tv_installations.room_area is 'Room / Area';
comment on column public.tv_installations.brand_and_model is 'Brand and Model Number';
comment on column public.tv_installations.serial_number is 'Serial Number';
comment on column public.tv_installations.validated_by is 'Validated by';
comment on column public.tv_installations.email is 'Email';

-- ---------------------------------------------------------------- links between tables
alter table public.projects add foreign key (job_owner_id) references public.contacts (id) on delete set null;
alter table public.projects add foreign key (building_id) references public.buildings (id) on delete set null;
alter table public.projects add foreign key (permit_id) references public.permits (id) on delete set null;
alter table public.projects add foreign key (design_firm_id) references public.organizations (id) on delete set null;
alter table public.projects add foreign key (lead_designer_id) references public.contacts (id) on delete set null;
alter table public.projects add foreign key (general_contractor_id) references public.organizations (id) on delete set null;
alter table public.projects add foreign key (gc_pm_id) references public.contacts (id) on delete set null;
alter table public.projects add foreign key (builder_developer_id) references public.organizations (id) on delete set null;
alter table public.projects add foreign key (referral_contact_id) references public.contacts (id) on delete set null;
alter table public.projects add foreign key (referral_organization_id) references public.organizations (id) on delete set null;
alter table public.projects add foreign key (maintenance_sales_person_id) references public.employees (id) on delete set null;
alter table public.contacts add foreign key (organization_id) references public.organizations (id) on delete set null;
alter table public.contacts add foreign key (referred_by_organization_id) references public.organizations (id) on delete set null;
alter table public.contacts add foreign key (referred_by_contact_id) references public.contacts (id) on delete set null;
alter table public.contacts add foreign key (referred_by_employee_id) references public.employees (id) on delete set null;
alter table public.contact_interactions add foreign key (contact_id) references public.contacts (id) on delete cascade;
alter table public.permits add foreign key (municipality_id) references public.organizations (id) on delete set null;
alter table public.permits add foreign key (project_id) references public.projects (id) on delete set null;
alter table public.permits add foreign key (owner_contact_id) references public.contacts (id) on delete set null;
alter table public.punch_list_items add foreign key (project_id) references public.projects (id) on delete set null;
alter table public.punch_list_items add foreign key (team_member_id) references public.employees (id) on delete set null;
alter table public.tasks add foreign key (member_id) references public.employees (id) on delete set null;
alter table public.rmas add foreign key (project_id) references public.projects (id) on delete set null;
alter table public.rmas add foreign key (manufacturer_id) references public.organizations (id) on delete set null;
alter table public.transactions add foreign key (project_id) references public.projects (id) on delete set null;
alter table public.transactions add foreign key (contact_id) references public.contacts (id) on delete set null;
alter table public.transactions add foreign key (organization_id) references public.organizations (id) on delete set null;
alter table public.inventory_checkouts add foreign key (project_id) references public.projects (id) on delete set null;
alter table public.inventory_checkouts add foreign key (technician_id) references public.employees (id) on delete set null;
alter table public.payouts add foreign key (employee_id) references public.employees (id) on delete set null;
alter table public.products add foreign key (supplier_id) references public.suppliers (id) on delete set null;
alter table public.products add foreign key (brand_id) references public.brands (id) on delete set null;
alter table public.sales add foreign key (stock_item_id) references public.stock_items (id) on delete set null;
alter table public.sales add foreign key (brand_id) references public.brands (id) on delete set null;
alter table public.sales add foreign key (destination_project_id) references public.projects (id) on delete set null;
alter table public.sales add foreign key (staff_id) references public.employees (id) on delete set null;
alter table public.stock_items add foreign key (product_id) references public.products (id) on delete set null;
alter table public.stock_items add foreign key (brand_id) references public.brands (id) on delete set null;
alter table public.stock_items add foreign key (destination_project_id) references public.projects (id) on delete set null;
alter table public.stock_items add foreign key (staff_id) references public.employees (id) on delete set null;
alter table public.support_notes add foreign key (ticket_id) references public.support_tickets (id) on delete cascade;
alter table public.kb_articles add foreign key (category_id) references public.kb_categories (id) on delete set null;
alter table public.job_reports add foreign key (project_id) references public.projects (id) on delete set null;
alter table public.job_reports add foreign key (vehicle_id) references public.vehicles (id) on delete set null;
alter table public.form_notes add foreign key (project_id) references public.projects (id) on delete set null;
alter table public.staff_performance add foreign key (employee_id) references public.employees (id) on delete set null;
alter table public.survey_proposals add foreign key (project_id) references public.projects (id) on delete set null;
alter table public.tv_installations add foreign key (project_id) references public.projects (id) on delete set null;

-- ---------------------------------------------------------------- many-to-many link tables
-- Articles › Audience (many)
create table public.kb_articles_audience_group (
  record_id bigint not null references public.kb_articles (id) on delete cascade,
  target_id smallint not null references public.groups (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (record_id, target_id)
);
create index on public.kb_articles_audience_group (target_id);
comment on table public.kb_articles_audience_group is 'Articles › Audience';
alter table public.kb_articles_audience_group enable row level security;
create policy "view" on public.kb_articles_audience_group for select to authenticated using (exists (select 1 from public.kb_articles r where r.id = record_id));
create policy "change" on public.kb_articles_audience_group for insert to authenticated with check (exists (select 1 from public.kb_articles r where r.id = record_id) and (select app.can_do('kb_articles', 'modify')));
create policy "remove" on public.kb_articles_audience_group for delete to authenticated using (exists (select 1 from public.kb_articles r where r.id = record_id) and (select app.can_do('kb_articles', 'modify')));

-- Job Report › Team (many)
create table public.job_reports_team (
  record_id bigint not null references public.job_reports (id) on delete cascade,
  target_id bigint not null references public.employees (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (record_id, target_id)
);
create index on public.job_reports_team (target_id);
comment on table public.job_reports_team is 'Job Report › Team';
alter table public.job_reports_team enable row level security;
create policy "view" on public.job_reports_team for select to authenticated using (exists (select 1 from public.job_reports r where r.id = record_id));
create policy "change" on public.job_reports_team for insert to authenticated with check (exists (select 1 from public.job_reports r where r.id = record_id) and (select app.can_do('job_reports', 'modify')));
create policy "remove" on public.job_reports_team for delete to authenticated using (exists (select 1 from public.job_reports r where r.id = record_id) and (select app.can_do('job_reports', 'modify')));

-- Job Report › Tag Someone (many)
create table public.job_reports_tagged (
  record_id bigint not null references public.job_reports (id) on delete cascade,
  target_id bigint not null references public.employees (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (record_id, target_id)
);
create index on public.job_reports_tagged (target_id);
comment on table public.job_reports_tagged is 'Job Report › Tag Someone';
alter table public.job_reports_tagged enable row level security;
create policy "view" on public.job_reports_tagged for select to authenticated using (exists (select 1 from public.job_reports r where r.id = record_id));
create policy "change" on public.job_reports_tagged for insert to authenticated with check (exists (select 1 from public.job_reports r where r.id = record_id) and (select app.can_do('job_reports', 'modify')));
create policy "remove" on public.job_reports_tagged for delete to authenticated using (exists (select 1 from public.job_reports r where r.id = record_id) and (select app.can_do('job_reports', 'modify')));

-- TV Installation › Team (many)
create table public.tv_installations_team (
  record_id bigint not null references public.tv_installations (id) on delete cascade,
  target_id bigint not null references public.employees (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (record_id, target_id)
);
create index on public.tv_installations_team (target_id);
comment on table public.tv_installations_team is 'TV Installation › Team';
alter table public.tv_installations_team enable row level security;
create policy "view" on public.tv_installations_team for select to authenticated using (exists (select 1 from public.tv_installations r where r.id = record_id));
create policy "change" on public.tv_installations_team for insert to authenticated with check (exists (select 1 from public.tv_installations r where r.id = record_id) and (select app.can_do('tv_installations', 'modify')));
create policy "remove" on public.tv_installations_team for delete to authenticated using (exists (select 1 from public.tv_installations r where r.id = record_id) and (select app.can_do('tv_installations', 'modify')));

-- ---------------------------------------------------------------- indexes
create index on public.projects (job_owner_id);
create index on public.projects (building_id);
create index on public.projects (permit_id);
create index on public.projects (design_firm_id);
create index on public.projects (lead_designer_id);
create index on public.projects (general_contractor_id);
create index on public.projects (gc_pm_id);
create index on public.projects (builder_developer_id);
create index on public.projects (referral_contact_id);
create index on public.projects (referral_organization_id);
create index on public.projects (maintenance_sales_person_id);
create index on public.projects (created_by);
create index on public.projects (updated_at desc);
create index on public.contacts (organization_id);
create index on public.contacts (referred_by_organization_id);
create index on public.contacts (referred_by_contact_id);
create index on public.contacts (referred_by_employee_id);
create index on public.contacts (created_by);
create index on public.contacts (updated_at desc);
create index on public.contact_interactions (contact_id);
create index on public.contact_interactions (created_by);
create index on public.contact_interactions (updated_at desc);
create index on public.buildings (created_by);
create index on public.buildings (updated_at desc);
create index on public.permits (municipality_id);
create index on public.permits (project_id);
create index on public.permits (owner_contact_id);
create index on public.permits (created_by);
create index on public.permits (updated_at desc);
create index on public.organizations (created_by);
create index on public.organizations (updated_at desc);
create index on public.punch_list_items (project_id);
create index on public.punch_list_items (team_member_id);
create index on public.punch_list_items (created_by);
create index on public.punch_list_items (updated_at desc);
create index on public.employees (created_by);
create index on public.employees (updated_at desc);
create index on public.vehicles (created_by);
create index on public.vehicles (updated_at desc);
create index on public.tasks (member_id);
create index on public.tasks (created_by);
create index on public.tasks (updated_at desc);
create index on public.rmas (project_id);
create index on public.rmas (manufacturer_id);
create index on public.rmas (created_by);
create index on public.rmas (updated_at desc);
create index on public.transactions (project_id);
create index on public.transactions (contact_id);
create index on public.transactions (organization_id);
create index on public.transactions (created_by);
create index on public.transactions (updated_at desc);
create index on public.inventory_checkouts (project_id);
create index on public.inventory_checkouts (technician_id);
create index on public.inventory_checkouts (created_by);
create index on public.inventory_checkouts (updated_at desc);
create index on public.payouts (employee_id);
create index on public.payouts (created_by);
create index on public.payouts (updated_at desc);
create index on public.products (supplier_id);
create index on public.products (brand_id);
create index on public.products (created_by);
create index on public.products (updated_at desc);
create index on public.sales (stock_item_id);
create index on public.sales (brand_id);
create index on public.sales (destination_project_id);
create index on public.sales (staff_id);
create index on public.sales (created_by);
create index on public.sales (updated_at desc);
create index on public.stock_items (product_id);
create index on public.stock_items (brand_id);
create index on public.stock_items (destination_project_id);
create index on public.stock_items (staff_id);
create index on public.stock_items (created_by);
create index on public.stock_items (updated_at desc);
create index on public.support_tickets (assigned_to);
create index on public.support_tickets (created_by);
create index on public.support_tickets (updated_at desc);
create index on public.support_notes (ticket_id);
create index on public.support_notes (assigned_to);
create index on public.support_notes (created_by);
create index on public.support_notes (updated_at desc);
create index on public.kb_articles (category_id);
create index on public.kb_articles (created_by);
create index on public.kb_articles (updated_at desc);
create index on public.suppliers (created_by);
create index on public.suppliers (updated_at desc);
create index on public.brands (created_by);
create index on public.brands (updated_at desc);
create index on public.kb_categories (created_by);
create index on public.kb_categories (updated_at desc);
create index on public.job_reports (project_id);
create index on public.job_reports (vehicle_id);
create index on public.job_reports (created_by);
create index on public.job_reports (updated_at desc);
create index on public.form_notes (project_id);
create index on public.form_notes (created_by);
create index on public.form_notes (updated_at desc);
create index on public.staff_performance (employee_id);
create index on public.staff_performance (created_by);
create index on public.staff_performance (updated_at desc);
create index on public.survey_proposals (project_id);
create index on public.survey_proposals (created_by);
create index on public.survey_proposals (updated_at desc);
create index on public.tv_installations (project_id);
create index on public.tv_installations (created_by);
create index on public.tv_installations (updated_at desc);

-- ---------------------------------------------------------------- permission catalogue
insert into app.record_types (table_name, label, module, resource, parent_table, parent_column, lock_resource, sensitive_columns) values
  ('projects', 'Projects', 'projects', 'projects', null, null, 'projects', array['system_credentials']),
  ('contacts', 'Contacts', 'projects', 'contacts', null, null, 'projects', '{}'),
  ('contact_interactions', 'Interactions', 'projects', null, 'contacts', 'contact_id', null, '{}'),
  ('buildings', 'Buildings / Developments', 'projects', 'buildings', null, null, 'projects', '{}'),
  ('permits', 'Permits', 'projects', 'permits', null, null, 'projects', '{}'),
  ('organizations', 'Organizations', 'projects', 'organizations', null, null, 'projects', array['portal_password']),
  ('punch_list_items', 'Punch List', 'projects', 'punch-list', null, null, 'projects', '{}'),
  ('employees', 'Employees', 'administrative', 'employees', null, null, 'records', array['ssn']),
  ('vehicles', 'Fleet', 'administrative', 'vehicles', null, null, 'records', '{}'),
  ('tasks', 'Tasks', 'administrative', 'tasks', null, null, 'records', '{}'),
  ('rmas', 'RMA', 'administrative', 'rma', null, null, 'records', '{}'),
  ('transactions', 'Transactions', 'administrative', 'transactions', null, null, 'records', '{}'),
  ('inventory_checkouts', 'Inventory Checkout', 'administrative', 'inventory-checkout', null, null, 'records', '{}'),
  ('payouts', 'Payroll', 'administrative', 'payroll', null, null, 'records', '{}'),
  ('products', 'Products', 'inventory', 'products', null, null, 'products', '{}'),
  ('sales', 'Sale', 'inventory', 'sales', null, null, 'products', '{}'),
  ('stock_items', 'Stock', 'inventory', 'stock', null, null, 'products', '{}'),
  ('support_tickets', 'Support Tickets', 'help-desk', 'tickets', null, null, 'tickets', '{}'),
  ('support_notes', 'Support Notes', 'help-desk', null, 'support_tickets', 'ticket_id', null, '{}'),
  ('kb_articles', 'Articles', 'help-desk', 'articles', null, null, 'tickets', '{}'),
  ('suppliers', 'Suppliers', 'utility', null, null, null, null, '{}'),
  ('brands', 'Brands', 'utility', null, null, null, null, '{}'),
  ('kb_categories', 'Knowledge Base Categories', 'utility', null, null, null, null, '{}'),
  ('job_reports', 'Job Report', 'forms', 'records', null, null, 'records', array['logins_and_passwords']),
  ('form_notes', 'Note', 'forms', 'records', null, null, 'records', '{}'),
  ('staff_performance', 'Staff Performance', 'forms', 'records', null, null, 'records', '{}'),
  ('survey_proposals', 'Survey and Proposals', 'forms', 'records', null, null, 'records', '{}'),
  ('tv_installations', 'TV Installation', 'forms', 'records', null, null, 'records', '{}');

-- ---------------------------------------------------------------- triggers and row-level security
-- Projects
create trigger before_write before insert or update on public.projects for each row execute function app.record_before_write();
create trigger audit after insert or update on public.projects for each row execute function app.record_audit();
alter table public.projects enable row level security;
create policy "view" on public.projects for select to authenticated using ((select app.can_view_all('projects')) or (created_by = (select auth.uid()) and (select app.can_view_page('projects'))));
create policy "create" on public.projects for insert to authenticated with check ((select app.can_do('projects', 'create')));
create policy "modify" on public.projects for update to authenticated using (((select app.can_view_all('projects')) or (created_by = (select auth.uid()) and (select app.can_view_page('projects')))) and ((select app.can_do('projects', 'modify')) or (select app.can_do('projects', 'delete')) or (select app.can_do('projects', 'archive')))) with check (((select app.can_do('projects', 'modify')) or (select app.can_do('projects', 'delete')) or (select app.can_do('projects', 'archive'))));

-- Contacts
create trigger before_write before insert or update on public.contacts for each row execute function app.record_before_write();
create trigger audit after insert or update on public.contacts for each row execute function app.record_audit();
alter table public.contacts enable row level security;
create policy "view" on public.contacts for select to authenticated using ((select app.can_view_all('contacts')) or (created_by = (select auth.uid()) and (select app.can_view_page('contacts'))));
create policy "create" on public.contacts for insert to authenticated with check ((select app.can_do('contacts', 'create')));
create policy "modify" on public.contacts for update to authenticated using (((select app.can_view_all('contacts')) or (created_by = (select auth.uid()) and (select app.can_view_page('contacts')))) and ((select app.can_do('contacts', 'modify')) or (select app.can_do('contacts', 'delete')) or (select app.can_do('contacts', 'archive')))) with check (((select app.can_do('contacts', 'modify')) or (select app.can_do('contacts', 'delete')) or (select app.can_do('contacts', 'archive'))));

-- Interactions
create trigger before_write before insert or update on public.contact_interactions for each row execute function app.record_before_write();
create trigger audit after insert or update on public.contact_interactions for each row execute function app.record_audit();
alter table public.contact_interactions enable row level security;
create policy "view" on public.contact_interactions for select to authenticated using (exists (select 1 from public.contacts p where p.id = contact_id));
create policy "create" on public.contact_interactions for insert to authenticated with check (exists (select 1 from public.contacts p where p.id = contact_id) and (select app.can_do('contact_interactions', 'create')));
create policy "modify" on public.contact_interactions for update to authenticated using (exists (select 1 from public.contacts p where p.id = contact_id) and (select app.can_do('contact_interactions', 'modify'))) with check (exists (select 1 from public.contacts p where p.id = contact_id));

-- Buildings / Developments
create trigger before_write before insert or update on public.buildings for each row execute function app.record_before_write();
create trigger audit after insert or update on public.buildings for each row execute function app.record_audit();
alter table public.buildings enable row level security;
create policy "view" on public.buildings for select to authenticated using ((select app.can_view_all('buildings')) or (created_by = (select auth.uid()) and (select app.can_view_page('buildings'))));
create policy "create" on public.buildings for insert to authenticated with check ((select app.can_do('buildings', 'create')));
create policy "modify" on public.buildings for update to authenticated using (((select app.can_view_all('buildings')) or (created_by = (select auth.uid()) and (select app.can_view_page('buildings')))) and ((select app.can_do('buildings', 'modify')) or (select app.can_do('buildings', 'delete')) or (select app.can_do('buildings', 'archive')))) with check (((select app.can_do('buildings', 'modify')) or (select app.can_do('buildings', 'delete')) or (select app.can_do('buildings', 'archive'))));

-- Permits
create trigger before_write before insert or update on public.permits for each row execute function app.record_before_write();
create trigger audit after insert or update on public.permits for each row execute function app.record_audit();
alter table public.permits enable row level security;
create policy "view" on public.permits for select to authenticated using ((select app.can_view_all('permits')) or (created_by = (select auth.uid()) and (select app.can_view_page('permits'))));
create policy "create" on public.permits for insert to authenticated with check ((select app.can_do('permits', 'create')));
create policy "modify" on public.permits for update to authenticated using (((select app.can_view_all('permits')) or (created_by = (select auth.uid()) and (select app.can_view_page('permits')))) and ((select app.can_do('permits', 'modify')) or (select app.can_do('permits', 'delete')) or (select app.can_do('permits', 'archive')))) with check (((select app.can_do('permits', 'modify')) or (select app.can_do('permits', 'delete')) or (select app.can_do('permits', 'archive'))));

-- Organizations
create trigger before_write before insert or update on public.organizations for each row execute function app.record_before_write();
create trigger audit after insert or update on public.organizations for each row execute function app.record_audit();
alter table public.organizations enable row level security;
create policy "view" on public.organizations for select to authenticated using ((select app.can_view_all('organizations')) or (created_by = (select auth.uid()) and (select app.can_view_page('organizations'))));
create policy "create" on public.organizations for insert to authenticated with check ((select app.can_do('organizations', 'create')));
create policy "modify" on public.organizations for update to authenticated using (((select app.can_view_all('organizations')) or (created_by = (select auth.uid()) and (select app.can_view_page('organizations')))) and ((select app.can_do('organizations', 'modify')) or (select app.can_do('organizations', 'delete')) or (select app.can_do('organizations', 'archive')))) with check (((select app.can_do('organizations', 'modify')) or (select app.can_do('organizations', 'delete')) or (select app.can_do('organizations', 'archive'))));

-- Punch List
create trigger before_write before insert or update on public.punch_list_items for each row execute function app.record_before_write();
create trigger audit after insert or update on public.punch_list_items for each row execute function app.record_audit();
alter table public.punch_list_items enable row level security;
create policy "view" on public.punch_list_items for select to authenticated using ((select app.can_view_all('punch_list_items')) or (created_by = (select auth.uid()) and (select app.can_view_page('punch_list_items'))));
create policy "create" on public.punch_list_items for insert to authenticated with check ((select app.can_do('punch_list_items', 'create')));
create policy "modify" on public.punch_list_items for update to authenticated using (((select app.can_view_all('punch_list_items')) or (created_by = (select auth.uid()) and (select app.can_view_page('punch_list_items')))) and ((select app.can_do('punch_list_items', 'modify')) or (select app.can_do('punch_list_items', 'delete')) or (select app.can_do('punch_list_items', 'archive')))) with check (((select app.can_do('punch_list_items', 'modify')) or (select app.can_do('punch_list_items', 'delete')) or (select app.can_do('punch_list_items', 'archive'))));

-- Employees
create trigger before_write before insert or update on public.employees for each row execute function app.record_before_write();
create trigger audit after insert or update on public.employees for each row execute function app.record_audit();
alter table public.employees enable row level security;
create policy "view" on public.employees for select to authenticated using ((select app.can_view_all('employees')) or (created_by = (select auth.uid()) and (select app.can_view_page('employees'))));
create policy "create" on public.employees for insert to authenticated with check ((select app.can_do('employees', 'create')));
create policy "modify" on public.employees for update to authenticated using (((select app.can_view_all('employees')) or (created_by = (select auth.uid()) and (select app.can_view_page('employees')))) and ((select app.can_do('employees', 'modify')) or (select app.can_do('employees', 'delete')) or (select app.can_do('employees', 'archive')))) with check (((select app.can_do('employees', 'modify')) or (select app.can_do('employees', 'delete')) or (select app.can_do('employees', 'archive'))));

-- Fleet
create trigger before_write before insert or update on public.vehicles for each row execute function app.record_before_write();
create trigger audit after insert or update on public.vehicles for each row execute function app.record_audit();
alter table public.vehicles enable row level security;
create policy "view" on public.vehicles for select to authenticated using ((select app.can_view_all('vehicles')) or (created_by = (select auth.uid()) and (select app.can_view_page('vehicles'))));
create policy "create" on public.vehicles for insert to authenticated with check ((select app.can_do('vehicles', 'create')));
create policy "modify" on public.vehicles for update to authenticated using (((select app.can_view_all('vehicles')) or (created_by = (select auth.uid()) and (select app.can_view_page('vehicles')))) and ((select app.can_do('vehicles', 'modify')) or (select app.can_do('vehicles', 'delete')) or (select app.can_do('vehicles', 'archive')))) with check (((select app.can_do('vehicles', 'modify')) or (select app.can_do('vehicles', 'delete')) or (select app.can_do('vehicles', 'archive'))));

-- Tasks
create trigger before_write before insert or update on public.tasks for each row execute function app.record_before_write();
create trigger audit after insert or update on public.tasks for each row execute function app.record_audit();
alter table public.tasks enable row level security;
create policy "view" on public.tasks for select to authenticated using ((select app.can_view_all('tasks')) or (created_by = (select auth.uid()) and (select app.can_view_page('tasks'))));
create policy "create" on public.tasks for insert to authenticated with check ((select app.can_do('tasks', 'create')));
create policy "modify" on public.tasks for update to authenticated using (((select app.can_view_all('tasks')) or (created_by = (select auth.uid()) and (select app.can_view_page('tasks')))) and ((select app.can_do('tasks', 'modify')) or (select app.can_do('tasks', 'delete')) or (select app.can_do('tasks', 'archive')))) with check (((select app.can_do('tasks', 'modify')) or (select app.can_do('tasks', 'delete')) or (select app.can_do('tasks', 'archive'))));

-- RMA
create trigger before_write before insert or update on public.rmas for each row execute function app.record_before_write();
create trigger audit after insert or update on public.rmas for each row execute function app.record_audit();
alter table public.rmas enable row level security;
create policy "view" on public.rmas for select to authenticated using ((select app.can_view_all('rmas')) or (created_by = (select auth.uid()) and (select app.can_view_page('rmas'))));
create policy "create" on public.rmas for insert to authenticated with check ((select app.can_do('rmas', 'create')));
create policy "modify" on public.rmas for update to authenticated using (((select app.can_view_all('rmas')) or (created_by = (select auth.uid()) and (select app.can_view_page('rmas')))) and ((select app.can_do('rmas', 'modify')) or (select app.can_do('rmas', 'delete')) or (select app.can_do('rmas', 'archive')))) with check (((select app.can_do('rmas', 'modify')) or (select app.can_do('rmas', 'delete')) or (select app.can_do('rmas', 'archive'))));

-- Transactions
create trigger before_write before insert or update on public.transactions for each row execute function app.record_before_write();
create trigger audit after insert or update on public.transactions for each row execute function app.record_audit();
alter table public.transactions enable row level security;
create policy "view" on public.transactions for select to authenticated using ((select app.can_view_all('transactions')) or (created_by = (select auth.uid()) and (select app.can_view_page('transactions'))));
create policy "create" on public.transactions for insert to authenticated with check ((select app.can_do('transactions', 'create')));
create policy "modify" on public.transactions for update to authenticated using (((select app.can_view_all('transactions')) or (created_by = (select auth.uid()) and (select app.can_view_page('transactions')))) and ((select app.can_do('transactions', 'modify')) or (select app.can_do('transactions', 'delete')) or (select app.can_do('transactions', 'archive')))) with check (((select app.can_do('transactions', 'modify')) or (select app.can_do('transactions', 'delete')) or (select app.can_do('transactions', 'archive'))));

-- Inventory Checkout
create trigger before_write before insert or update on public.inventory_checkouts for each row execute function app.record_before_write();
create trigger audit after insert or update on public.inventory_checkouts for each row execute function app.record_audit();
alter table public.inventory_checkouts enable row level security;
create policy "view" on public.inventory_checkouts for select to authenticated using ((select app.can_view_all('inventory_checkouts')) or (created_by = (select auth.uid()) and (select app.can_view_page('inventory_checkouts'))));
create policy "create" on public.inventory_checkouts for insert to authenticated with check ((select app.can_do('inventory_checkouts', 'create')));
create policy "modify" on public.inventory_checkouts for update to authenticated using (((select app.can_view_all('inventory_checkouts')) or (created_by = (select auth.uid()) and (select app.can_view_page('inventory_checkouts')))) and ((select app.can_do('inventory_checkouts', 'modify')) or (select app.can_do('inventory_checkouts', 'delete')) or (select app.can_do('inventory_checkouts', 'archive')))) with check (((select app.can_do('inventory_checkouts', 'modify')) or (select app.can_do('inventory_checkouts', 'delete')) or (select app.can_do('inventory_checkouts', 'archive'))));

-- Payroll
create trigger before_write before insert or update on public.payouts for each row execute function app.record_before_write();
create trigger audit after insert or update on public.payouts for each row execute function app.record_audit();
alter table public.payouts enable row level security;
create policy "view" on public.payouts for select to authenticated using ((select app.can_view_all('payouts')) or (created_by = (select auth.uid()) and (select app.can_view_page('payouts'))));
create policy "create" on public.payouts for insert to authenticated with check ((select app.can_do('payouts', 'create')));
create policy "modify" on public.payouts for update to authenticated using (((select app.can_view_all('payouts')) or (created_by = (select auth.uid()) and (select app.can_view_page('payouts')))) and ((select app.can_do('payouts', 'modify')) or (select app.can_do('payouts', 'delete')) or (select app.can_do('payouts', 'archive')))) with check (((select app.can_do('payouts', 'modify')) or (select app.can_do('payouts', 'delete')) or (select app.can_do('payouts', 'archive'))));

-- Products
create trigger before_write before insert or update on public.products for each row execute function app.record_before_write();
create trigger audit after insert or update on public.products for each row execute function app.record_audit();
alter table public.products enable row level security;
create policy "view" on public.products for select to authenticated using ((select app.can_view_all('products')) or (created_by = (select auth.uid()) and (select app.can_view_page('products'))));
create policy "create" on public.products for insert to authenticated with check ((select app.can_do('products', 'create')));
create policy "modify" on public.products for update to authenticated using (((select app.can_view_all('products')) or (created_by = (select auth.uid()) and (select app.can_view_page('products')))) and ((select app.can_do('products', 'modify')) or (select app.can_do('products', 'delete')) or (select app.can_do('products', 'archive')))) with check (((select app.can_do('products', 'modify')) or (select app.can_do('products', 'delete')) or (select app.can_do('products', 'archive'))));

-- Sale
create trigger before_write before insert or update on public.sales for each row execute function app.record_before_write();
create trigger audit after insert or update on public.sales for each row execute function app.record_audit();
alter table public.sales enable row level security;
create policy "view" on public.sales for select to authenticated using ((select app.can_view_all('sales')) or (created_by = (select auth.uid()) and (select app.can_view_page('sales'))));
create policy "create" on public.sales for insert to authenticated with check ((select app.can_do('sales', 'create')));
create policy "modify" on public.sales for update to authenticated using (((select app.can_view_all('sales')) or (created_by = (select auth.uid()) and (select app.can_view_page('sales')))) and ((select app.can_do('sales', 'modify')) or (select app.can_do('sales', 'delete')) or (select app.can_do('sales', 'archive')))) with check (((select app.can_do('sales', 'modify')) or (select app.can_do('sales', 'delete')) or (select app.can_do('sales', 'archive'))));

-- Stock
create trigger before_write before insert or update on public.stock_items for each row execute function app.record_before_write();
create trigger audit after insert or update on public.stock_items for each row execute function app.record_audit();
alter table public.stock_items enable row level security;
create policy "view" on public.stock_items for select to authenticated using ((select app.can_view_all('stock_items')) or (created_by = (select auth.uid()) and (select app.can_view_page('stock_items'))));
create policy "create" on public.stock_items for insert to authenticated with check ((select app.can_do('stock_items', 'create')));
create policy "modify" on public.stock_items for update to authenticated using (((select app.can_view_all('stock_items')) or (created_by = (select auth.uid()) and (select app.can_view_page('stock_items')))) and ((select app.can_do('stock_items', 'modify')) or (select app.can_do('stock_items', 'delete')) or (select app.can_do('stock_items', 'archive')))) with check (((select app.can_do('stock_items', 'modify')) or (select app.can_do('stock_items', 'delete')) or (select app.can_do('stock_items', 'archive'))));

-- Support Tickets
create trigger before_write before insert or update on public.support_tickets for each row execute function app.record_before_write();
create trigger audit after insert or update on public.support_tickets for each row execute function app.record_audit();
alter table public.support_tickets enable row level security;
create policy "view" on public.support_tickets for select to authenticated using ((select app.can_view_all('support_tickets')) or (created_by = (select auth.uid()) and (select app.can_view_page('support_tickets'))));
create policy "create" on public.support_tickets for insert to authenticated with check ((select app.can_do('support_tickets', 'create')));
create policy "modify" on public.support_tickets for update to authenticated using (((select app.can_view_all('support_tickets')) or (created_by = (select auth.uid()) and (select app.can_view_page('support_tickets')))) and ((select app.can_do('support_tickets', 'modify')) or (select app.can_do('support_tickets', 'delete')) or (select app.can_do('support_tickets', 'archive')))) with check (((select app.can_do('support_tickets', 'modify')) or (select app.can_do('support_tickets', 'delete')) or (select app.can_do('support_tickets', 'archive'))));

-- Support Notes
create trigger before_write before insert or update on public.support_notes for each row execute function app.record_before_write();
create trigger audit after insert or update on public.support_notes for each row execute function app.record_audit();
alter table public.support_notes enable row level security;
create policy "view" on public.support_notes for select to authenticated using (exists (select 1 from public.support_tickets p where p.id = ticket_id));
create policy "create" on public.support_notes for insert to authenticated with check (exists (select 1 from public.support_tickets p where p.id = ticket_id) and (select app.can_do('support_notes', 'create')));
create policy "modify" on public.support_notes for update to authenticated using (exists (select 1 from public.support_tickets p where p.id = ticket_id) and (select app.can_do('support_notes', 'modify'))) with check (exists (select 1 from public.support_tickets p where p.id = ticket_id));

-- Articles
create trigger before_write before insert or update on public.kb_articles for each row execute function app.record_before_write();
create trigger audit after insert or update on public.kb_articles for each row execute function app.record_audit();
alter table public.kb_articles enable row level security;
create policy "view" on public.kb_articles for select to authenticated using ((select app.can_view_all('kb_articles')) or (created_by = (select auth.uid()) and (select app.can_view_page('kb_articles'))));
create policy "create" on public.kb_articles for insert to authenticated with check ((select app.can_do('kb_articles', 'create')));
create policy "modify" on public.kb_articles for update to authenticated using (((select app.can_view_all('kb_articles')) or (created_by = (select auth.uid()) and (select app.can_view_page('kb_articles')))) and ((select app.can_do('kb_articles', 'modify')) or (select app.can_do('kb_articles', 'delete')) or (select app.can_do('kb_articles', 'archive')))) with check (((select app.can_do('kb_articles', 'modify')) or (select app.can_do('kb_articles', 'delete')) or (select app.can_do('kb_articles', 'archive'))));

-- Suppliers
create trigger before_write before insert or update on public.suppliers for each row execute function app.record_before_write();
create trigger audit after insert or update on public.suppliers for each row execute function app.record_audit();
alter table public.suppliers enable row level security;
create policy "view" on public.suppliers for select to authenticated using (true);
create policy "create" on public.suppliers for insert to authenticated with check ((select app.can_manage_utility()));
create policy "modify" on public.suppliers for update to authenticated using ((select app.can_manage_utility())) with check ((select app.can_manage_utility()));

-- Brands
create trigger before_write before insert or update on public.brands for each row execute function app.record_before_write();
create trigger audit after insert or update on public.brands for each row execute function app.record_audit();
alter table public.brands enable row level security;
create policy "view" on public.brands for select to authenticated using (true);
create policy "create" on public.brands for insert to authenticated with check ((select app.can_manage_utility()));
create policy "modify" on public.brands for update to authenticated using ((select app.can_manage_utility())) with check ((select app.can_manage_utility()));

-- Knowledge Base Categories
create trigger before_write before insert or update on public.kb_categories for each row execute function app.record_before_write();
create trigger audit after insert or update on public.kb_categories for each row execute function app.record_audit();
alter table public.kb_categories enable row level security;
create policy "view" on public.kb_categories for select to authenticated using (true);
create policy "create" on public.kb_categories for insert to authenticated with check ((select app.can_manage_utility()));
create policy "modify" on public.kb_categories for update to authenticated using ((select app.can_manage_utility())) with check ((select app.can_manage_utility()));

-- Job Report
create trigger before_write before insert or update on public.job_reports for each row execute function app.record_before_write();
create trigger audit after insert or update on public.job_reports for each row execute function app.record_audit();
alter table public.job_reports enable row level security;
create policy "view" on public.job_reports for select to authenticated using ((select app.can_view_all('job_reports')) or (created_by = (select auth.uid()) and (select app.can_view_page('job_reports'))));
create policy "create" on public.job_reports for insert to authenticated with check ((select app.can_do('job_reports', 'create')));
create policy "modify" on public.job_reports for update to authenticated using (((select app.can_view_all('job_reports')) or (created_by = (select auth.uid()) and (select app.can_view_page('job_reports')))) and ((select app.can_do('job_reports', 'modify')) or (select app.can_do('job_reports', 'delete')) or (select app.can_do('job_reports', 'archive')))) with check (((select app.can_do('job_reports', 'modify')) or (select app.can_do('job_reports', 'delete')) or (select app.can_do('job_reports', 'archive'))));

-- Note
create trigger before_write before insert or update on public.form_notes for each row execute function app.record_before_write();
create trigger audit after insert or update on public.form_notes for each row execute function app.record_audit();
alter table public.form_notes enable row level security;
create policy "view" on public.form_notes for select to authenticated using ((select app.can_view_all('form_notes')) or (created_by = (select auth.uid()) and (select app.can_view_page('form_notes'))));
create policy "create" on public.form_notes for insert to authenticated with check ((select app.can_do('form_notes', 'create')));
create policy "modify" on public.form_notes for update to authenticated using (((select app.can_view_all('form_notes')) or (created_by = (select auth.uid()) and (select app.can_view_page('form_notes')))) and ((select app.can_do('form_notes', 'modify')) or (select app.can_do('form_notes', 'delete')) or (select app.can_do('form_notes', 'archive')))) with check (((select app.can_do('form_notes', 'modify')) or (select app.can_do('form_notes', 'delete')) or (select app.can_do('form_notes', 'archive'))));

-- Staff Performance
create trigger before_write before insert or update on public.staff_performance for each row execute function app.record_before_write();
create trigger audit after insert or update on public.staff_performance for each row execute function app.record_audit();
alter table public.staff_performance enable row level security;
create policy "view" on public.staff_performance for select to authenticated using ((select app.can_view_all('staff_performance')) or (created_by = (select auth.uid()) and (select app.can_view_page('staff_performance'))));
create policy "create" on public.staff_performance for insert to authenticated with check ((select app.can_do('staff_performance', 'create')));
create policy "modify" on public.staff_performance for update to authenticated using (((select app.can_view_all('staff_performance')) or (created_by = (select auth.uid()) and (select app.can_view_page('staff_performance')))) and ((select app.can_do('staff_performance', 'modify')) or (select app.can_do('staff_performance', 'delete')) or (select app.can_do('staff_performance', 'archive')))) with check (((select app.can_do('staff_performance', 'modify')) or (select app.can_do('staff_performance', 'delete')) or (select app.can_do('staff_performance', 'archive'))));

-- Survey and Proposals
create trigger before_write before insert or update on public.survey_proposals for each row execute function app.record_before_write();
create trigger audit after insert or update on public.survey_proposals for each row execute function app.record_audit();
alter table public.survey_proposals enable row level security;
create policy "view" on public.survey_proposals for select to authenticated using ((select app.can_view_all('survey_proposals')) or (created_by = (select auth.uid()) and (select app.can_view_page('survey_proposals'))));
create policy "create" on public.survey_proposals for insert to authenticated with check ((select app.can_do('survey_proposals', 'create')));
create policy "modify" on public.survey_proposals for update to authenticated using (((select app.can_view_all('survey_proposals')) or (created_by = (select auth.uid()) and (select app.can_view_page('survey_proposals')))) and ((select app.can_do('survey_proposals', 'modify')) or (select app.can_do('survey_proposals', 'delete')) or (select app.can_do('survey_proposals', 'archive')))) with check (((select app.can_do('survey_proposals', 'modify')) or (select app.can_do('survey_proposals', 'delete')) or (select app.can_do('survey_proposals', 'archive'))));

-- TV Installation
create trigger before_write before insert or update on public.tv_installations for each row execute function app.record_before_write();
create trigger audit after insert or update on public.tv_installations for each row execute function app.record_audit();
alter table public.tv_installations enable row level security;
create policy "view" on public.tv_installations for select to authenticated using ((select app.can_view_all('tv_installations')) or (created_by = (select auth.uid()) and (select app.can_view_page('tv_installations'))));
create policy "create" on public.tv_installations for insert to authenticated with check ((select app.can_do('tv_installations', 'create')));
create policy "modify" on public.tv_installations for update to authenticated using (((select app.can_view_all('tv_installations')) or (created_by = (select auth.uid()) and (select app.can_view_page('tv_installations')))) and ((select app.can_do('tv_installations', 'modify')) or (select app.can_do('tv_installations', 'delete')) or (select app.can_do('tv_installations', 'archive')))) with check (((select app.can_do('tv_installations', 'modify')) or (select app.can_do('tv_installations', 'delete')) or (select app.can_do('tv_installations', 'archive'))));

-- ---------------------------------------------------------------- computed fields
-- Projects › Approved / Invoiced / Paid: sums of Transactions (SPEC §2.3). Runs with owner rights so the
-- totals show even to people who can't open Transactions, but only for projects the caller may see.
create function public.project_financials(p_project_ids bigint[])
returns table (project_id bigint, approved_amount numeric, invoiced_amount numeric, paid_amount numeric)
language sql stable security definer set search_path = ''
as $$
  select p.id,
    coalesce(sum(t.amount) filter (where t.type = 'Proposal'), 0),
    coalesce(sum(t.amount) filter (where t.type = 'Invoice'), 0),
    coalesce(sum(t.amount) filter (where t.type = 'Payment'), 0)
  from public.projects p
  left join public.transactions t on t.project_id = p.id and t.deleted_at is null
  where p.id = any (p_project_ids)
    and (app.can_view_all('projects') or (p.created_by = auth.uid() and app.can_view_page('projects')))
  group by p.id;
$$;
revoke execute on function public.project_financials(bigint[]) from public, anon;
grant execute on function public.project_financials(bigint[]) to authenticated;
