-- F23 Documents (SPEC §9.1 F23, Fred 2026-10-07): the company's important papers (operating licences,
-- insurance certificates, workers' comp…) as files with a title, grouped by category on a board.
-- The old CRM's "WIKI" tab. Everyone can see them; the office keeps them.
create table public.company_documents (
  id bigint generated by default as identity primary key,
  title text,
  category text,
  expires_on date,
  notes text,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz
);
comment on table public.company_documents is 'Documents — the company''s licences, insurance and other papers, one file each (F23, not from WebAuthor)';
comment on column public.company_documents.title is 'Title';
comment on column public.company_documents.category is 'Category';
comment on column public.company_documents.expires_on is 'Expires on';
comment on column public.company_documents.notes is 'Notes';
create index on public.company_documents (category);
create index on public.company_documents (expires_on);

insert into app.record_types (table_name, label, module, resource, parent_table, parent_column, lock_resource, sensitive_columns)
values ('company_documents', 'Documents', 'administrative', 'documents', null, null, null, '{}');

create trigger before_write before insert or update on public.company_documents for each row execute function app.record_before_write();
create trigger audit after insert or update on public.company_documents for each row execute function app.record_audit();

alter table public.company_documents enable row level security;
create policy "view" on public.company_documents for select to authenticated using ((select app.can_view_all('company_documents')) or (created_by = (select auth.uid()) and (select app.can_view_page('company_documents'))));
create policy "create" on public.company_documents for insert to authenticated with check ((select app.can_do('company_documents', 'create')));
create policy "modify" on public.company_documents for update to authenticated using (((select app.can_view_all('company_documents')) or (created_by = (select auth.uid()) and (select app.can_view_page('company_documents')))) and ((select app.can_do('company_documents', 'modify')) or (select app.can_do('company_documents', 'delete')) or (select app.can_do('company_documents', 'archive')))) with check (((select app.can_do('company_documents', 'modify')) or (select app.can_do('company_documents', 'delete')) or (select app.can_do('company_documents', 'archive'))));

insert into public.permissions (key, module, resource, action, kind, area, label, description) values
  ('administrative.documents.view_page', 'administrative', 'documents', 'view_page', 'page', 'Documents', 'Documents', 'See the company documents board (licences, insurance…)'),
  ('administrative.documents.view_all', 'administrative', 'documents', 'view_all', 'action', 'Documents', 'Documents: View All', 'See every document, not only the ones you added'),
  ('administrative.documents.create', 'administrative', 'documents', 'create', 'action', 'Documents', 'Documents: Add', 'Add documents'),
  ('administrative.documents.modify', 'administrative', 'documents', 'modify', 'action', 'Documents', 'Documents: Modify', 'Change documents'),
  ('administrative.documents.delete', 'administrative', 'documents', 'delete', 'action', 'Documents', 'Documents: Delete', 'Delete documents (they can be restored)'),
  ('administrative.documents.archive', 'administrative', 'documents', 'archive', 'action', 'Documents', 'Documents: Archive', 'Archive and unarchive documents');

-- Everyone with a login sees the board (a technician may have to show the insurance certificate at a building).
insert into public.user_permissions (user_id, permission_key)
select p.id, k
from public.profiles p
cross join unnest(array['administrative.documents.view_page', 'administrative.documents.view_all']) k
on conflict do nothing;
-- The office keeps the documents. Administrators always can.
insert into public.user_permissions (user_id, permission_key)
select p.id, k
from public.profiles p
cross join unnest(array['administrative.documents.create', 'administrative.documents.modify', 'administrative.documents.archive', 'administrative.documents.delete']) k
where lower(p.email) in ('jessica@tsav.net', 'luana@tsav.net', 'lucas@tsav.net', 'saulo@tsav.net')
on conflict do nothing;
