-- F13 Job costing (SPEC §9.1 F13-a/b): pay rates per employee over time, and one permission that
-- gates everything about costs. Fred 2026-10-03: "job costing only available for Lucas, Saulo, Fred,
-- Jessica and Luana. No other member should see it."

-- The permission (shows in the per-person checklist under Pages).
insert into public.permissions (key, module, resource, action, kind, area, label, description)
values ('job_costing.view', 'job_costing', 'page', 'view', 'page', 'Job costing', 'Job costing', 'Costs, pay rates and margin per project (Project › Job costing, Employee › Pay rate)');

insert into public.user_permissions (user_id, permission_key)
select id, 'job_costing.view'
from public.profiles
where lower(email) in ('fred@tsav.net', 'lucas@tsav.net', 'saulo@tsav.net', 'jessica@tsav.net', 'luana@tsav.net')
on conflict do nothing;

-- Pay rates: a new row each time a rate changes; the rate in force on a date is the latest effective_from <= date.
create table public.employee_pay_rates (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees (id) on delete cascade,
  hourly_rate numeric(12,2) not null check (hourly_rate >= 0),
  effective_from date not null default (now() at time zone 'America/New_York')::date,
  note text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  unique (employee_id, effective_from)
);
create index on public.employee_pay_rates (employee_id, effective_from desc);
comment on table public.employee_pay_rates is 'F13-a: hourly pay rate per employee, with history; only job_costing.view may read or write';

alter table public.employee_pay_rates enable row level security;
create policy "job costing reads pay rates" on public.employee_pay_rates for select to authenticated using (app.has_permission('job_costing.view'));
create policy "job costing adds pay rates" on public.employee_pay_rates for insert to authenticated with check (app.has_permission('job_costing.view'));
create policy "job costing changes pay rates" on public.employee_pay_rates for update to authenticated using (app.has_permission('job_costing.view')) with check (app.has_permission('job_costing.view'));
create policy "job costing removes pay rates" on public.employee_pay_rates for delete to authenticated using (app.has_permission('job_costing.view'));
grant select, insert, update, delete on public.employee_pay_rates to authenticated;
