-- F18 Visit = Report rule (SPEC §9.1 F18-a…d).
--
--   report_deficiencies   one row per person and visit when the Job Report was Late or Missing;
--                         Admin / COO can excuse it with a reason (History keeps the audit)
--   sms_outbox            every SMS (Twilio), queued → sent / failed; test mode like email
--   automations 900601    the nightly jobs run as this row (9 PM reminders, midnight close) → automation_runs
--   automations 900602    a Job Report added: the Late check (action report_rule)
--   app_settings field_day.report_rule   { mode: off | dry_run | live, since: date }

-- ---------------------------------------------------------------- report deficiencies
create table public.report_deficiencies (
  id bigint generated by default as identity primary key,
  title text,
  employee_id bigint not null references public.employees (id) on delete cascade,
  date date not null,
  project_id bigint references public.projects (id) on delete set null,
  visit_id bigint references public.visits (id) on delete set null,
  type text not null check (type in ('Late', 'Missing')),
  status text not null default 'Open' check (status in ('Open', 'Excused')),
  report_id bigint references public.job_reports (id) on delete set null,
  performance_id bigint references public.staff_performance (id) on delete set null,
  excuse_reason text,
  excused_by uuid references public.profiles (id) on delete set null,
  excused_at timestamptz,
  locked boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid() references public.profiles (id) on delete set null,
  archived_at timestamptz,
  deleted_at timestamptz,
  unique (employee_id, visit_id)
);
comment on table public.report_deficiencies is 'Report Deficiencies — a Job Report that was Late or Missing for a visit (F18, not from WebAuthor)';
create index on public.report_deficiencies (employee_id, date desc);
create index on public.report_deficiencies (project_id);
create index on public.report_deficiencies (status);

insert into app.record_types (table_name, label, module, resource, parent_table, parent_column, lock_resource, sensitive_columns)
values ('report_deficiencies', 'Report Deficiencies', 'administrative', 'report-deficiencies', null, null, null, '{}');

create trigger before_write before insert or update on public.report_deficiencies for each row execute function app.record_before_write();
create trigger audit after insert or update on public.report_deficiencies for each row execute function app.record_audit();

alter table public.report_deficiencies enable row level security;
create policy "view" on public.report_deficiencies for select to authenticated using ((select app.can_view_all('report_deficiencies')) or (created_by = (select auth.uid()) and (select app.can_view_page('report_deficiencies'))));
create policy "create" on public.report_deficiencies for insert to authenticated with check ((select app.can_do('report_deficiencies', 'create')));
create policy "modify" on public.report_deficiencies for update to authenticated using (((select app.can_view_all('report_deficiencies')) or (created_by = (select auth.uid()) and (select app.can_view_page('report_deficiencies')))) and ((select app.can_do('report_deficiencies', 'modify')) or (select app.can_do('report_deficiencies', 'delete')) or (select app.can_do('report_deficiencies', 'archive')))) with check (((select app.can_do('report_deficiencies', 'modify')) or (select app.can_do('report_deficiencies', 'delete')) or (select app.can_do('report_deficiencies', 'archive'))));

insert into public.permissions (key, module, resource, action, kind, area, label, description) values
  ('administrative.report-deficiencies.view_page', 'administrative', 'report-deficiencies', 'view_page', 'page', 'Report Deficiencies', 'Report Deficiencies', 'See late and missing Job Reports'),
  ('administrative.report-deficiencies.view_all', 'administrative', 'report-deficiencies', 'view_all', 'action', 'Report Deficiencies', 'Report Deficiencies: View All', 'See every deficiency, not only the ones you created'),
  ('administrative.report-deficiencies.modify', 'administrative', 'report-deficiencies', 'modify', 'action', 'Report Deficiencies', 'Report Deficiencies: Excuse', 'Excuse a deficiency with a reason (Admin / COO)'),
  ('administrative.report-deficiencies.delete', 'administrative', 'report-deficiencies', 'delete', 'action', 'Report Deficiencies', 'Report Deficiencies: Delete', 'Delete deficiencies (they can be restored)'),
  ('administrative.report-deficiencies.archive', 'administrative', 'report-deficiencies', 'archive', 'action', 'Report Deficiencies', 'Report Deficiencies: Archive', 'Archive and unarchive deficiencies');

-- The office sees the list; Lucas and Saulo (COO) can excuse. Administrators always can.
insert into public.user_permissions (user_id, permission_key)
select p.id, k
from public.profiles p
cross join unnest(array['administrative.report-deficiencies.view_page', 'administrative.report-deficiencies.view_all']) k
where lower(p.email) in ('jessica@tsav.net', 'luana@tsav.net', 'lucas@tsav.net', 'saulo@tsav.net')
on conflict do nothing;
insert into public.user_permissions (user_id, permission_key)
select p.id, 'administrative.report-deficiencies.modify'
from public.profiles p
where lower(p.email) in ('lucas@tsav.net', 'saulo@tsav.net')
on conflict do nothing;

-- ---------------------------------------------------------------- sms outbox
create table public.sms_outbox (
  id uuid primary key default gen_random_uuid(),
  kind text not null default 'report_reminder',
  employee_id bigint references public.employees (id) on delete set null,
  visit_id bigint references public.visits (id) on delete set null,
  to_number text not null,
  body text not null,
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed')),
  test_mode boolean not null default false,
  provider_id text,
  error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);
create index sms_outbox_status_idx on public.sms_outbox (status, created_at);
create index sms_outbox_employee_idx on public.sms_outbox (employee_id, created_at desc);
alter table public.sms_outbox enable row level security;
create policy "office reads" on public.sms_outbox for select to authenticated using ((select app.can_view_all('report_deficiencies')));

-- ---------------------------------------------------------------- settings and automations
update public.app_settings
set value = value || '{"report_rule": {"mode": "off", "since": null}}'::jsonb
where key = 'field_day' and not (value ? 'report_rule');

insert into public.automations (id, table_name, title, active, events, conditions, actions, notes) values
(900601, 'visits', 'Report rule: 9 PM reminders and midnight close', true, '{}',
  '{"match":"all","rules":[]}', '[]',
  'F18: runs on the hourly tick (9:01 PM Eastern: one SMS per missing report; 12:01 AM: Missing deficiencies for the day before). Mode and start date in Admin › Field day.'),
(900602, 'job_reports', 'Report rule: late report', true, '{added}',
  '{"match":"all","rules":[]}',
  '[{"type":"report_rule"}]',
  'F18: a report filed after the visit''s day creates (or turns a Missing into) a Late deficiency for each team member.')
on conflict (id) do nothing;

-- The tick claims the nightly steps like the other slots (scheduled_runs keys reports_sms:<date>, reports_close:<date>).
alter table public.scheduled_runs drop constraint if exists scheduled_runs_kind_check;
alter table public.scheduled_runs add constraint scheduled_runs_kind_check check (kind in ('daily', 'hourly', 'google', 'reports_sms', 'reports_close'));
