-- M2: users, groups and permissions (SPEC §7).
--
-- Model
--   profiles           one row per login (auth.users), created automatically
--   groups             the 12 WebAuthor groups
--   group_members      which users are in which groups
--   permissions        catalogue of permission keys, e.g. 'projects.contacts.create'
--   group_permissions  which groups hold which keys
--
-- Rules
--   * Every signed-in user is implicitly in "everyone".
--   * Members of "system_administrators" have every permission.
--   * RLS policies everywhere call app.has_permission(key).

create schema if not exists app;
grant usage on schema app to authenticated;

-- ---------------------------------------------------------------- tables

create table public.groups (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  legacy_code text,
  is_system boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
comment on table public.groups is 'User groups carried over from WebAuthor (SPEC §7.2).';

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  first_name text,
  last_name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.profiles is 'One row per login. Created by trigger when an auth user is created.';

create table public.group_members (
  group_id smallint not null references public.groups (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (group_id, user_id)
);
create index group_members_user_idx on public.group_members (user_id);

create table public.permissions (
  key text primary key,
  module text not null,
  resource text not null,
  action text not null,
  kind text not null check (kind in ('page', 'action', 'pod')),
  area text not null,
  label text not null,
  description text not null default ''
);
comment on table public.permissions is 'Permission catalogue generated from the WebAuthor export.';

create table public.group_permissions (
  group_id smallint not null references public.groups (id) on delete cascade,
  permission_key text not null references public.permissions (key) on delete cascade,
  primary key (group_id, permission_key)
);
create index group_permissions_key_idx on public.group_permissions (permission_key);

-- ---------------------------------------------------------------- helper functions
-- SECURITY DEFINER so they can read membership tables regardless of the caller's RLS.
-- search_path is pinned to '' and every object is schema-qualified.

create function app.is_sysadmin(p_user uuid default auth.uid())
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1
    from public.group_members gm
    join public.groups g on g.id = gm.group_id
    join public.profiles p on p.id = gm.user_id
    where gm.user_id = p_user and g.slug = 'system_administrators' and g.active and p.active
  );
$$;

create function app.has_permission(p_key text, p_user uuid default auth.uid())
returns boolean
language sql stable security definer set search_path = ''
as $$
  select p_user is not null
    and exists (select 1 from public.profiles where id = p_user and active)
    and (
      app.is_sysadmin(p_user)
      or exists (
        select 1
        from public.group_permissions gp
        join public.groups g on g.id = gp.group_id and g.active
        where gp.permission_key = p_key
          and (
            g.slug = 'everyone'
            or exists (select 1 from public.group_members gm where gm.group_id = g.id and gm.user_id = p_user)
          )
      )
    );
$$;

-- Every permission key the current user holds; the UI uses this to build menus.
create function public.my_permissions()
returns text[]
language sql stable security definer set search_path = ''
as $$
  select case
    when auth.uid() is null or not exists (select 1 from public.profiles where id = auth.uid() and active)
      then array[]::text[]
    when app.is_sysadmin() then (select coalesce(array_agg(key order by key), array[]::text[]) from public.permissions)
    else (
      select coalesce(array_agg(distinct gp.permission_key order by gp.permission_key), array[]::text[])
      from public.group_permissions gp
      join public.groups g on g.id = gp.group_id and g.active
      where g.slug = 'everyone'
         or exists (select 1 from public.group_members gm where gm.group_id = g.id and gm.user_id = auth.uid())
    )
  end;
$$;

revoke execute on function app.is_sysadmin(uuid), app.has_permission(text, uuid), public.my_permissions() from public, anon;
grant execute on function app.is_sysadmin(uuid), app.has_permission(text, uuid), public.my_permissions() to authenticated;

-- ---------------------------------------------------------------- profile trigger

create function app.handle_new_user()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email, first_name, last_name)
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data ->> 'first_name', ''),
    nullif(new.raw_user_meta_data ->> 'last_name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function app.handle_new_user();

-- Users created before this migration (e.g. the first admin login).
insert into public.profiles (id, email)
select id, email from auth.users
on conflict (id) do nothing;

create function app.touch_updated_at()
returns trigger
language plpgsql set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_touch before update on public.profiles
  for each row execute function app.touch_updated_at();

-- ---------------------------------------------------------------- RLS
-- Reading: any signed-in user (names appear on records; groups/permissions build menus).
-- Writing: System Administrators, or holders of the WebAuthor site-admin "Members"/"Groups" pages.

alter table public.groups enable row level security;
alter table public.profiles enable row level security;
alter table public.group_members enable row level security;
alter table public.permissions enable row level security;
alter table public.group_permissions enable row level security;

create policy "signed-in users read groups" on public.groups
  for select to authenticated using (true);
create policy "group admins manage groups" on public.groups
  for all to authenticated
  using (app.has_permission('site.admin.groups'))
  with check (app.has_permission('site.admin.groups'));

create policy "signed-in users read profiles" on public.profiles
  for select to authenticated using (true);
create policy "users update own name" on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());
create policy "member admins manage profiles" on public.profiles
  for update to authenticated
  using (app.has_permission('site.admin.members'))
  with check (app.has_permission('site.admin.members'));

create policy "signed-in users read memberships" on public.group_members
  for select to authenticated using (true);
create policy "group admins manage memberships" on public.group_members
  for all to authenticated
  using (app.has_permission('site.admin.groups'))
  with check (app.has_permission('site.admin.groups'));

create policy "signed-in users read permissions" on public.permissions
  for select to authenticated using (true);

create policy "signed-in users read grants" on public.group_permissions
  for select to authenticated using (true);
create policy "permission admins manage grants" on public.group_permissions
  for all to authenticated
  using (app.is_sysadmin())
  with check (app.is_sysadmin());

-- Users may change their own name but not their email or active flag.
create function app.guard_profile_update()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  if not app.has_permission('site.admin.members')
     and (new.email is distinct from old.email or new.active is distinct from old.active) then
    raise exception 'Only member administrators can change email or active status';
  end if;
  return new;
end;
$$;

create trigger profiles_guard before update on public.profiles
  for each row execute function app.guard_profile_update();
