-- M10: automations (WebAuthor "triggers", SPEC §5) and the email outbox.
--
-- automations        one row per trigger: events, conditions, actions (JSON, editable in M12)
-- automation_runs    log of every time an automation matched a record
-- email_outbox       every email the app sends (or would send, in test mode)
-- audit_log.automation_status   null = not yet looked at by the engine; the engine processes
--                               new history entries after each request (and on a schedule, M11)

create table public.automations (
  id bigint primary key,                 -- WebAuthor trigger id (e.g. 694)
  table_name text not null,
  title text not null,
  active boolean not null default true,
  -- 'added' | 'modified' | 'field:<column>' | 'daily' | 'hourly'
  events text[] not null,
  -- { "match": "all" | "any", "rules": [ { "field", "op", "value" | "field2", "days": bool } ] }
  conditions jsonb not null default '{"match": "all", "rules": []}',
  -- [ { "type": "update" | "email" | "checklist" | "archive", ... } ]
  actions jsonb not null,
  notes text,
  updated_at timestamptz not null default now()
);

create table public.automation_runs (
  id bigint generated by default as identity primary key,
  automation_id bigint not null references public.automations (id) on delete cascade,
  table_name text not null,
  record_id bigint not null,
  event text not null,
  status text not null check (status in ('done', 'error')),
  detail jsonb not null default '{}',
  at timestamptz not null default now()
);
create index automation_runs_record_idx on public.automation_runs (table_name, record_id, at desc);
create index automation_runs_automation_idx on public.automation_runs (automation_id, at desc);

create table public.email_outbox (
  id uuid primary key default gen_random_uuid(),
  automation_id bigint references public.automations (id) on delete set null,
  table_name text,
  record_id bigint,
  from_address text not null,
  to_addresses text[] not null,
  cc_addresses text[] not null default '{}',
  bcc_addresses text[] not null default '{}',
  subject text not null,
  html text not null,
  -- [{ "kind": "file", "path", "name" } | { "kind": "record_pdf" }]
  attachments jsonb not null default '[]',
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed')),
  test_mode boolean not null default false,
  provider_id text,
  error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);
create index email_outbox_status_idx on public.email_outbox (status, created_at);

alter table public.audit_log add column automation_status text check (automation_status in ('done', 'skipped'));
create index audit_log_pending_idx on public.audit_log (id) where automation_status is null;
-- History written before automations existed doesn't need processing.
update public.audit_log set automation_status = 'skipped' where automation_status is null;

-- Admin screens (M12) read these; only System Administrators change them. The engine uses the service role.
alter table public.automations enable row level security;
alter table public.automation_runs enable row level security;
alter table public.email_outbox enable row level security;
create policy "admins read" on public.automations for select to authenticated using (app.has_permission('projects.module.design_triggers'));
create policy "sysadmins manage" on public.automations for all to authenticated using (app.is_sysadmin()) with check (app.is_sysadmin());
create policy "admins read" on public.automation_runs for select to authenticated using (app.has_permission('projects.module.design_triggers'));
create policy "admins read" on public.email_outbox for select to authenticated using (app.has_permission('projects.module.design_triggers'));
