-- INV-b Inventory import (SPEC §9.1 INV-b): the Sortly export and the later sales export land in the CRM.
-- Fred 2026-10-04: "o estoque segue como vem do Sortly" (quantities per location), one product per
-- distinct name / SKU, serials noted on the checkout line, Sortly price → cost.
--
-- 1. Quantities per location live in a ledger (stock_movements), never in an editable number: the
--    import writes opening balances, Phase 2 adds ins / outs, and stock_levels sums them.
-- 2. Imported rows carry a source key (source_ref) so the import can be re-run without duplicates.
-- 3. Products gain a Description (the sales export's "Type": "SUBWOOFER EPISODE 12 DARK BROWN").

alter table public.products add column description text, add column source_ref text;
comment on column public.products.description is 'Description';
create unique index products_source_ref_key on public.products (source_ref) where source_ref is not null;

alter table public.stock_items add column source_ref text;
create unique index stock_items_source_ref_key on public.stock_items (source_ref) where source_ref is not null;

alter table public.inventory_checkouts add column source_ref text;
create unique index inventory_checkouts_source_ref_key on public.inventory_checkouts (source_ref) where source_ref is not null;

create table public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  location text not null default '',
  quantity numeric(12,2) not null,
  kind text not null check (kind in ('opening', 'in', 'out', 'adjust')),
  serial text,
  reference text,
  notes text,
  moved_at timestamptz not null default now(),
  source_ref text unique,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references public.profiles (id) on delete set null
);
create index on public.stock_movements (product_id, location);
comment on table public.stock_movements is 'INV-b: stock ledger. On hand per product and location = sum(quantity); opening rows come from the Sortly / sales imports, later rows from checkouts and purchases (Phase 2). Never edited in place.';

alter table public.stock_movements enable row level security;
-- Anyone who may open the Stock list reads the ledger; writes come from the engines (service role) until Phase 2.
create policy "stock viewers read movements" on public.stock_movements for select to authenticated using ((select app.can_view_page('stock_items')));
grant select on public.stock_movements to authenticated;

create view public.stock_levels with (security_invoker = true) as
select product_id, location, sum(quantity) as on_hand, count(serial) filter (where serial is not null) as serials, max(moved_at) as last_moved_at
from public.stock_movements
group by product_id, location
having sum(quantity) <> 0;
comment on view public.stock_levels is 'INV-b: on hand per product and location, summed from stock_movements';
grant select on public.stock_levels to authenticated;
